
Title (13-words or less): Hydrological Drought Assessment of Heterogenious Catchments with Short Periods of Record  

<!--
## Variable naming convention:   

gage            USGS stream gages with daily values 
    _dv         daily values; used for the first set of gages selected
    _meta       metadata
      _ck       a check on the values
      _incomp   incomplete year 
      _xx       number of the model run as new dv gets added
    _fill       estimated dvs based on PCfill values for estimated dvs 
      _dups     potential or actual duplicate dv values 
    _miss       missing gaging stations; sused to fill with estimated dvs 
    _pairs      nearest average PC1 & PC2 
 
lambda_vals     lambda vals from the Box Cox for PCA input 

last_dv         the last

pca 
    _eigen      fraction explained by eigenvectors 
    _input      dv depths for pca 
    _sum        summary of mean values following PCA 
    _vars       eigenvalues from PCA 

test            variable used to test breaks or errors in code 

vals 
    _eigen      table of fraction explained by eigenvectors by run 
    _input      table of dv depths for pca by run 
    _sum        table of summary of mean values following PCA by run 
    _vars       table of eigenvalues from PCA by run 

year
    _length     table of lengths of water years by station 
      _ck       check of length; also used to append the table of lengths 
    _sum        water year and days of record in a wide format
    _summary    water year and days of record 
-->

```{r setup, include=FALSE, message=FALSE}  
#knitr::opts_chunk$set(echo = FALSE)    
options(tibble.print_max = 70) # sets tibble output for printing  

# Sets up the library of packages   
library("here")          # identifies where to save work  
library("lubridate")     # easier dates 
library("tidyverse")     # data munging tools 
library("janitor")       # tools for examining and cleaning dirty data  
library("dataRetrieval") # USGS data import  
library("forecast")      # for BoxCox 
library("broom")         # sweep up PCA results into tidy frames 
library("beepr")         # plays notification sounds 
library("mclust") 
library("factoextra") 
```

```{r fill_miss_dates, message=FALSE} 
# 1. load daily flow data    
gage_dv_raw <- read_csv("data/gage_dv.csv") %>%  
  clean_names() %>%  
  filter(sta != "elk_rob")           # remove the record of crystaline basins  

wkc_wok <- gage_dv_raw %>%  
  filter(sta == "wkc_wok")  

# 2. check for complete days of record & years of record  
yr_incomp <- gage_dv_raw %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_yr = n()) %>%                    
  ungroup() %>%  
  filter(between(days_yr, .8 * 360, 364))  

# 3. fill the station-years with missing data  
wy_1991 <- tibble(date = seq.Date(from=as.Date("1990-10-01"),  
                 to=as.Date("1991-09-30"), by="day")) 

wy_2003 <- tibble(date = seq.Date(from=as.Date("2002-10-01"),  
                 to=as.Date("2003-09-30"), by="day")) 

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
bev_pri_1991 <- gage_dv_raw %>%  
  filter(sta == "bev_pri") %>%  
  filter(water_year == 1991) 

bev_pri_1991 <- full_join(bev_pri_1991, wy_1991) 

bev_pri_1991 <- bev_pri_1991 %>%  
  mutate(sta = "bev_pri") %>%  
  mutate(incomp_yr = "Y") %>%  
  mutate(water_year = 1991) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
whi_slm_1991 <- gage_dv_raw %>%  
  filter(sta == "whi_slm") %>%  
  filter(water_year == 1991) 

whi_slm_1991 <- full_join(whi_slm_1991, wy_1991) 

whi_slm_1991 <- whi_slm_1991 %>%  
  mutate(sta = "whi_slm") %>%  
  mutate(incomp_yr = "Y") %>%  
  mutate(water_year = 1991) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
lwr_aro_2003 <- gage_dv_raw %>%  
  filter(sta == "lwr_aro") %>%  
  filter(water_year == 2003) 

lwr_aro_2003 <- full_join(lwr_aro_2003 , wy_2003) 

lwr_aro_2003 <- lwr_aro_2003 %>%  
  mutate(sta = "lwr_aro") %>%   
  mutate(incomp_yr = "Y") %>%   
  mutate(water_year = 2003) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  

# 4. append and join data  
yr_dv_incomp <- bind_rows(bev_pri_1991, whi_slm_1991, lwr_aro_2003) 

gage_dv <- bind_rows(yr_dv_incomp, gage_dv_raw) %>%  
  distinct() %>%  
  group_by(sta, water_year) %>%                  
  mutate(days_yr = n()) %>%                   
  ungroup()   

# 4. remove short years  
gage_dv_incomp <-  gage_dv %>% 
  filter(days_yr < 365) 

gage_dv <- gage_dv %>% 
  filter(days_yr >= 365)  

# 5. check results  
gage_ck <- gage_dv %>%  
  filter(sta == "lwr_aro") %>%  
  filter(water_year == "2003") 

yr_sum <- gage_dv %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_yr = n()) %>%                    
  ungroup() 

# 6. clean up  
rm(bev_pri_1991, gage_dv_incomp, gage_dv_raw, lwr_aro_2003, whi_slm_1991, 
   wy_1991, wy_2003, yr_dv_incomp, yr_incomp, wkc_wok, gage_ck)  
``` 

```{r censor_low_flows, message=FALSE} 
 
# 1. fix low flows ---- this step needed for the PCA  
#   EGRET calculates a "better" zero-flow value, but causes issues with results 
#   this code chunk fixes low flow values by substituting 0.01 cfs 
#   for zero-flow values  
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  

# 2.1. censor zero flows to 0.01 cfs 
# gather the different flow values 
gage_dv_gath <- gage_dv %>%  # using diff var name to check length later 
  gather(key = q_type, val = q_val,       # prepares to censor to 0.01 cfs
         -c(sta, water_year, date, incomp_yr)) 

gage_dv_ck <- gage_dv_gath %>%
  distinct()

# 2.2. filter & censor zero flows 
gage_dv_low <- gage_dv_gath %>% 
  filter(q_val < 0.01) %>%               
  mutate(q_val = 0.01) 

# 2.3. filter non-zero flows 
gage_dv_high <- gage_dv_gath %>% 
  filter(q_val >= 0.01) %>% 
  mutate(q_val = round(.$q_val, digits = 2))

# 2.4. join the zero and non-zero together 
gage_dv_gath <- bind_rows(gage_dv_high, gage_dv_low) 

# 2.5. spread out the different flows 
gage_dv <- gage_dv_gath %>% 
  spread(q_type, q_val) 

# 2.6. check the data for duplicates & clean up 
gage_ck <- gage_dv %>%  
  group_by(sta, water_year) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  filter(count > 366) 

rm(gage_dv_ck, gage_dv_gath, gage_dv_high, gage_dv_low, gage_ck)
``` 

```{r prepare_for_clustering, message=FALSE}  

# 1. make summaries of the incomplete and complete years
yr_sum_comp <-  gage_dv %>% 
  filter(incomp_yr == "N") %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_record = n()) %>%                   
  ungroup()   

yr_sum_incomp <- gage_dv %>% 
  filter(incomp_yr == "Y") %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_record = n()) %>%                   
  ungroup()   

# 2. split stations with missing vals from gage_dv           
gage_miss_yr <- semi_join(gage_dv, yr_sum_incomp, 
                          by = "sta") 

gage_comp_yr <- anti_join(gage_dv, yr_sum_incomp, 
                          by = "sta")     

# 3. find which months are missing  
gage_miss_mon <- gage_miss_yr %>% 
  select(-c(water_year, incomp_yr, days_yr)) %>% 
  gather(type, val, -c(sta, date)) %>% 
  mutate(month = month(date)) %>% 
  group_by(sta, month) %>% 
  filter(is.na(val)) %>% 
  group_by(sta) %>% 
  summarize(first = first(month),
            last = last(month)) %>% 
  arrange(first) %>% 
  arrange(last) 

# 3. separate the missing months from the missing years 
gage_miss_10 <- gage_miss_yr %>% 
  mutate(month = month(date)) %>%  
  filter(month == 10) 

gage_miss_11 <- gage_miss_yr %>% 
  mutate(month = month(date)) %>%  
  filter(month == 11) %>% 
  filter(sta == "lwr_aro" | 
         sta == "whi_sta") 

gage_miss_12 <- gage_miss_yr %>% 
  mutate(month = month(date)) %>%  
  filter(month == 12) %>% 
  filter(sta == "whi_sta")

# 3.1 join the missing months & update the complete data 
gage_miss_mon <- bind_rows(gage_miss_10, gage_miss_11, gage_miss_12)

gage_comp_mon <- anti_join(gage_miss_yr, gage_miss_mon)

gage_comp_mon <- bind_rows(gage_comp_yr, gage_comp_mon)

# 3.2 check results
gage_ck <- gage_miss_mon %>% 
  filter(sta == "lwr_aro") %>% 
  filter(water_year == "2003")

# 4.0. calculate missing values based on monthly averages    
gage_miss_sum <- gage_miss_mon %>% 
  group_by(sta, month) %>% 
  summarize(q_fill = 10^mean(log(q), na.rm = TRUE), 
            q7_fill = 10^mean(log(q7), na.rm = TRUE),
            q30_fill = 10^mean(log(q30), na.rm = TRUE)
            ) %>% 
  ungroup() %>% 
  mutate(q_fill = round(q_fill, digits = 2)) %>% 
  mutate(q7_fill = round(q7_fill, digits = 2)) %>% 
  mutate(q30_fill = round(q30_fill, digits = 2)) 

# 5. join missing values & fill NAs
gage_miss_mon <- left_join(gage_miss_mon, gage_miss_sum,
                           by = c("sta", "month"))

gage_miss_mon <- gage_miss_mon %>% 
  mutate(q = case_when(
    is.na(q) ~ q_fill, 
    TRUE ~ q)
    ) %>% 
  mutate(q7 = case_when(
    is.na(q7) ~ q7_fill, 
    TRUE ~ q7)
    ) %>% 
  mutate(q30 = case_when(
    is.na(q30) ~ q30_fill, 
    TRUE ~ q30)
    ) %>% 
  select(-c(q_fill, q7_fill, q30_fill)) 

# 6. check results & append filled data
gage_dv2 <- bind_rows(gage_comp_mon, gage_miss_mon)

gage_dv <- gage_dv2 %>% 
  select(-month)

gage_dv <- gage_dv %>% 
  group_by(sta, water_year) %>% 
  mutate(days_yr = n()) %>% 
  ungroup() %>% 
  mutate(incomp_yr = case_when( 
    days_yr < 365 ~ "Y", 
    TRUE ~ "N" 
  )) 

summary(gage_dv) 

# 7. filter out NAs in gage_dv & find which months are missing
gage_miss_mon <- gage_dv %>% 
  select(-incomp_yr) %>% 
  gather(type, discharge, -c(sta, date, water_year)) %>% 
  filter(is.na(discharge)) %>% 
  spread(type, discharge) %>% 
  mutate(month = month(date)) %>% 
  group_by(sta) %>% 
  summarize(first = first(month),
            last = last(month)) %>% 
  arrange(first) %>% 
  arrange(last) %>% 
  ungroup()

# 8.1. make a summary table of average missing values & prepare join 
gage_dv_fill <- gage_dv %>% 
  filter(sta == "bev_pri" | 
         sta == "whi_slm"
         ) %>% 
  mutate(month = month(date)) %>% 
  group_by(sta, month) %>% 
  summarize(q_fill = 10^mean(log(q), na.rm = TRUE), 
            q7_fill = 10^mean(log(q7), na.rm = TRUE),
            q30_fill = 10^mean(log(q30), na.rm = TRUE)
            ) %>% 
  ungroup() %>% 
  mutate(q_fill = round(q_fill, digits = 2)) %>% 
  mutate(q7_fill = round(q7_fill, digits = 2)) %>% 
  mutate(q30_fill = round(q30_fill, digits = 2)) 

# 8.3 separate incomplete & complete stations 
gage_dv_incomp_sta <- gage_dv %>% 
  filter(sta == "bev_pri" | 
         sta == "whi_slm"
         ) %>% 
  mutate(month = month(date)) 

gage_dv_comp_sta <- gage_dv %>% 
  filter(sta != "bev_pri" & 
         sta != "whi_slm"
         )

# 8.2 join to gage & fill NAs
gage_dv_incomp_sta <- right_join(gage_dv_incomp_sta, gage_dv_fill, 
                       by = c("sta", "month"))

gage_dv_incomp_sta <- gage_dv_incomp_sta %>% 
  mutate(q = case_when(
    is.na(q) ~ q_fill, 
    TRUE ~ q)
    ) %>% 
  mutate(q7 = case_when(
    is.na(q7) ~ q7_fill, 
    TRUE ~ q7)
    ) %>% 
  mutate(q30 = case_when(
    is.na(q30) ~ q30_fill, 
    TRUE ~ q30)
    ) %>% 
  select(-c(q_fill, q7_fill, q30_fill)) 

gage_dv <- bind_rows(gage_dv_comp_sta, gage_dv_incomp_sta) %>% 
  select(-c(incomp_yr, days_yr, month)) 

gage_dv <- gage_dv %>% 
  filter(sta != "nio_mar")                    # only 5 years record 

# 8.3 change any zero flows to 0.01 
gage_dv <- gage_dv %>% 
  gather(type, discharge, -c(sta, date, water_year)) %>% 
  mutate(discharge = case_when(
    discharge == 0 ~ 0.01, 
    TRUE ~ discharge) 
  ) %>% 
  spread(type, discharge)

# 9. update summaries & fix gap years 
yr_sum <- gage_dv %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_yr = n()) %>%                   
  ungroup() %>% 
  group_by(sta) 
 
yr_len <- yr_sum %>% 
  group_by(sta) %>% 
  summarize(min_yr = min(water_year), 
            max_yr = max(water_year),
            yrs_record = n() + 1) %>%                   
  ungroup() %>% 
  mutate(diff_yrs = 2 + max_yr - min_yr) %>% 
  mutate(yr_gap = case_when(
    yrs_record == diff_yrs ~ "N", 
    TRUE ~ "Y"
  )) %>% 
  arrange(desc(yr_gap))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
yr_len <- yr_len %>% 
  mutate(min_yr = case_when(
    sta == "che_buf" ~ 2008, 
    sta == "che_pla" ~ 2001,
    sta == "wcc_ogl" ~ 1988,
    TRUE ~ min_yr
  )) %>% 
  mutate(max_yr = case_when(
    sta == "lwr_aro" ~ 1999, 
    TRUE ~ max_yr
  ))

# 10. clean up 
rm(gage_comp_yr, gage_miss_yr, gage_ck, gage_miss_10, gage_miss_11, 
   gage_miss_12, gage_miss_sum, gage_comp_mon, gage_miss_mon, 
   gage_dv2, gage_dv_fill, gage_dv_comp_sta, gage_dv_incomp_sta,
   yr_sum_comp, yr_sum_incomp)
 
```

```{r convert_to_flow_depth, message = FALSE} 

# 1. get metadata
gage_meta <- read_csv("data/gage_dv_meta.csv")  %>% 
  mutate(site_no = as.character(site_no)) %>% 
  mutate(site_no = zeroPad(site_no, 8)) 

gage_contrib_area <- gage_meta %>% 
  select(sta, drain_area_va, contrib_drain_area_va) %>% 
  mutate(contrib_drain_area_va = 
           contrib_drain_area_va %>% 
             is.na %>%
             ifelse(drain_area_va, contrib_drain_area_va)) %>% 
  select(-drain_area_va) %>% 
    mutate(contrib_drain_area_km = round(contrib_drain_area_va * 2.59, 
                                         digits = 1)) %>% 
  select(-contrib_drain_area_va)

# 2. bind catchment area to gage_dv 
gage_dv <- left_join(gage_dv, gage_contrib_area, by = "sta") 
 
# 3. eliminate effects of watershed size---- 
# Calculate daily flow depths by dividing flow (cms) by watershed 
#    area (sq-km) and multiplying the resultant by the number of 
#    seconds in a day.  The result is cu-m-d per sq-km. 
 
gage_dv <- gage_dv %>% 
  mutate(q1_depth = round(q * (60*60*24) / contrib_drain_area_km, 
                          digits = 2)) %>% 
  mutate(q7_depth = round(q7 * (60*60*24) / contrib_drain_area_km, 
                          digits = 2)) %>% 
  mutate(q30_depth = round(q30 * (60*60*24) / contrib_drain_area_km, 
                           digits = 2))   

# 4. convert to log depths---- 
gage_dv <- gage_dv %>% 
  mutate(log_q1_depth = round(log10(q1_depth), digits = 2) 
         ) %>% 
  mutate(log_q7_depth = round(log10(q7_depth), digits = 2)
         ) %>%            
  mutate(log_q30_depth = round(log10(q30_depth), digits = 2)
         )    
``` 

```{r prepare_model_counter}
# 1. make an original dv dataframe
gage_dv <- gage_dv %>% 
  mutate(water_year = as.numeric(water_year))

gage_dv_orig <- gage_dv        # for run 

# 2. prepare counter for model runs 

i = 0 
```

# model starts here 
```{r Mclust_model}
 
# 1. set values for run  
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
i <- i +1                       # update tracking counter 
run_name <- paste0("run_0", i)  # update run name 

yr_len <- yr_len %>% 
  arrange(yrs_record) 

yr_min <- as_vector(yr_len %>% 
                      select(min_yr) %>% 
                      slice(1) 
                    )  

yr_max <- as_vector(yr_len %>%  
                      select(max_yr) %>% 
                      slice(1) 
                    ) 

yr_lag <- as_vector(yr_min - 1) 
yr_lead <- as_vector(yr_max + 1) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  

# 2.0. find stations for cluster run 
clust_sum <- yr_len %>% 
  filter(min_yr <= yr_min) %>% 
  filter(max_yr >= yr_max) 

# 2. prepare for model run 
clust_dv <- semi_join(gage_dv, clust_sum, 
                      by = "sta") %>% 
  select(sta, date, log_q1_depth:log_q30_depth) %>% 
  arrange(date) 

# 3. create input for the model run 
input <- clust_dv %>% 
  group_by(sta) %>% 
  summarize(log_q1_depth = mean(log_q1_depth), 
            log_q7_depth = mean(log_q7_depth), 
            log_q30_depth = mean(log_q30_depth) 
            ) 

# 1. prepare model input 
X <- input %>%                # this gets rid of categorical data for Mclust 
  select(-sta) 

# 2. calculate bic 
BIC <- mclustBIC(X) 

mod <- Mclust(X, x = BIC) 

#jsonedit(mod, mode = "view", elementId = "mod1") 

# 3. prepare run inputs for join  
input <- input %>% 
  gather(type, discharge, -sta) %>% 
  mutate(discharge = round(discharge, digits = 3) 
         ) %>% 
  spread(type, discharge) 

clust_sum <- clust_sum %>% 
  mutate(run = as.character(run_name)) 

# 4. prepare model summary outputs & join 
num_clust <- enframe(mod$G, value = "num_clust", name = NULL) 
num_obs   <- enframe(mod$n, value = "num_obs", name = NULL) 
df        <- enframe(mod$df, value = "df", name = NULL) 
mod_nm    <- enframe(mod$modelName, value = "mod_nm", name = NULL) 
bic       <- enframe(mod$bic, value = "bic", name = NULL) 
loglik    <- enframe(mod$loglik, value = "loglik", name = NULL) 

mod_sum   <- bind_cols(mod_nm, num_clust, num_obs, df,  bic, loglik) 

# 5. get model means and variance, join & clean up 
params <- pluck(mod$parameters) 

# 6. prepare to collect output data 
cluster   <- enframe(mod$classification, value = "clust", name = "rowname") 

input <- input %>%  
  rownames_to_column() %>%  
  mutate(rowname = as.integer(rowname)) 

# 6. join input and output 
output <- full_join(input, cluster, by = "rowname") %>% 
  select(-rowname) %>% 
  arrange(log_q1_depth) %>% 
  arrange(clust) %>% 
  mutate(run = as.character(run_name))  


# 7.0  prepare to join lead and lag stations by creating lead and lag  
#      cluster columns 
gage_pairs <- output %>% 
  mutate(clust_lead1 = lead(clust, 
                     n = 1L, default = 0)) %>%   # creates a lead col 
  mutate(clust_lag1 = lag(clust, 
                     n = 1L, default = 0)) %>%   # creates a lag col 
  mutate(clust_lead2 = lead(clust, 
                     n = 2L, default = 0)) %>%   # creates a lead2 col  
  mutate(clust_lag2 = lag(clust, 
                     n = 2L, default = 0)) %>%    # creates a lag2 col 
  mutate(clust_lead3 = lead(clust, 
                     n = 3L, default = 0)) %>%   # creates a lead3 col 
  mutate(clust_lag3 = lag(clust, 
                     n = 3L, default = 0))   # creates a lag3 col 

# 7.1.  create lead and lag stations for same clusters - NA for diff clusters 
gage_pairs <- gage_pairs %>%  
  mutate(sta_lead1 = case_when( 
    clust == clust_lead1 ~ lead(sta, n = 1L, default = 0), 
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>%  
  mutate(sta_lag1 = case_when( 
    clust == clust_lag1 ~ lag(sta, n = 1L, default = 0), 
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>% 
  mutate(sta_lead2 = case_when( 
    clust == clust_lead2 ~ lead(sta, n = 2L, default = 0), 
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>%  
  mutate(sta_lag2 = case_when( 
    clust == clust_lag2 ~ lag(sta, n = 2L, default = 0), 
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>% 
  mutate(sta_lead3 = case_when( 
    clust == clust_lead3 ~ lead(sta, n = 3L, default = 0),
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>%  
  mutate(sta_lag3 = case_when( 
    clust == clust_lag3 ~ lag(sta, n = 3L, default = 0), 
    TRUE ~ "NA")                                # creates a lead1 sta 
    ) %>% 
  select(sta, sta_lead1, sta_lag1, sta_lead2, sta_lag2, 
         sta_lead3, sta_lag3) 

# 7.2.  gather the pairs to prepare to join the q1-q30 vals  
#     note: exploratory PCA showed that q1 vals are strongest predictors  
#     however, the q30 was most important for our results 
gage_pairs <- gage_pairs %>%  
  gather(key, value = sta_pair, -sta) %>% 
  mutate(sta_pair = na_if(sta_pair, "NA")) %>% 
  drop_na(sta_pair) %>% 
  select(-key) 

# 7.3.  join the q1-q30 vals for the stations 
gage_pairs <- full_join(gage_pairs, output, 
                        by = "sta") 

# 7.4.  join the q1-q30 vals for the station pairs & calculate diffs 
gage_pairs <- full_join(gage_pairs, output, 
                        by = c("sta_pair" = "sta")) %>% 
  rename(log_q30_depth  = log_q30_depth.x) %>% 
  rename(clust = clust.x) %>% 
  rename(log_q30_pair   = log_q30_depth.y) %>% 
  select(sta, clust, sta_pair, log_q30_depth, log_q30_pair) %>% 
  mutate(log_q30_diff = round(abs(log_q30_depth - log_q30_pair), 
                             digits = 4) 
         ) %>% 
  arrange(log_q30_diff) 

# 7.5.  join the year lengths for sta & sta_pair 
gage_pairs <- left_join(gage_pairs, yr_len, 
                         by = "sta") 

gage_pairs <- left_join(gage_pairs, yr_len, 
                         by = c("sta_pair" = "sta")) 

# 7.6. clean up the var names 
gage_pairs <- gage_pairs %>% 
  rename(min_yr_sta = min_yr.x) %>% 
  rename(max_yr_sta = max_yr.x) %>% 
  rename(yrs_record_sta = yrs_record.x) %>% 
  rename(yr_gap_sta = yr_gap.x) %>% 
  rename(min_yr_pair = min_yr.y) %>% 
  rename(max_yr_pair = max_yr.y) %>% 
  rename(yrs_record_pair = yrs_record.y) %>% 
  rename(yr_gap_pair = yr_gap.y) %>% 
  select(-c(diff_yrs.x, diff_yrs.y))  


# 8.1 find the best fit lag pair 
miss_lag <- gage_pairs %>% 
  filter(yr_lag < min_yr_sta) %>%  
  filter(yr_lag >= min_yr_pair) %>%  
  group_by(sta) %>% 
  summarise(sta_pair = first(sta_pair)) %>% 
  ungroup() %>% 
  mutate(water_year = yr_lag) 

# 8.2 find the best fit lead pair 
miss_lead <- gage_pairs %>% 
  filter(yr_lead > max_yr_sta) %>% 
  filter(yr_lead <= max_yr_pair) %>% 
  arrange(log_q30_diff) %>% 
  group_by(sta) %>% 
  summarise(sta_pair = first(sta_pair)) %>% 
  ungroup() %>% 
  mutate(water_year = yr_lead) 

# 8.3. join the missing stations 
gage_fill <- bind_rows(miss_lag, miss_lead) 

# 8.4. get fill dvs 
gage_fill_dv <- right_join(gage_dv, gage_fill, 
                                   by = c("sta" = "sta_pair", 
                                          "water_year")) %>% 
  rename(sta_fill = sta) %>% 
  rename(sta = sta.y)    %>% 
  select(sta, date, water_year, everything()) %>% 
  select(-contrib_drain_area_km) 

# 8.5. calculate q, q7, q30 for the filled vals 
gage_fill_dv <- left_join(gage_fill_dv, gage_contrib_area, 
                  by = "sta") %>% 
  mutate(q   = q1_depth   * contrib_drain_area_km / (60 * 60 * 24)) %>% 
  mutate(q7  = q7_depth  * contrib_drain_area_km / (60 * 60 * 24)) %>% 
  mutate(q30 = q30_depth * contrib_drain_area_km / (60 * 60 * 24)) %>% 
  mutate(q = case_when( 
    q < 0.01 ~ 0.01, 
    TRUE ~ round(q, digits = 2) 
    )) %>% 
  mutate(q7 = case_when( 
    q7 < 0.01 ~ 0.01, 
    TRUE ~ round(q7, digits = 2) 
    )) %>% 
  mutate(q30 = case_when(  
    q30 < 0.01 ~ 0.01, 
    TRUE ~ round(q7, digits = 2)  
    )) %>% 
  select(-sta_fill)  
```

```{r check_Mclust_results}
summary(mod, parameters = TRUE)  
#plot(BIC) 

plot(mod, what = "classification") 

fviz_mclust(mod, "classification", geom = "point", ellipse.type = "t", 
            ellipse.level = 0.7, pointsize = 1,  palatte = "aaas") 
 
# 1.0 check the fill vals 
gage_fill <- gage_fill %>% 
  arrange(sta) 

print(gage_fill$sta)  

# 1.1 prepare to plot the existing dvs 
gage_ck <- gage_dv %>% 
  filter( 
#         sta == "bev_abf" |     # run_01 
#         sta == "blp_bel" |     # run_01 
#         sta == "ros_ros" |     # run_01 
#         sta == "whi_slm" |     # run_01 
#         sta == "wkc_wok"       # run_01 
         ) %>% 
  filter(between(water_year, yr_lag, yr_lead)) 

# 1.2 plot the existing dvs
#ggplot(gage_ck, aes(date, q30_depth)) + 
#  geom_line(aes(color = sta)) +
#  facet_grid(sta ~ .) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

# 2.0 add in the fill dvs  
gage_ck <- bind_rows(gage_ck, gage_fill_dv) %>% 
  arrange(date) 

# 2.1 plot the fill & existing dvs  
ggplot(gage_ck, aes(date, q30_depth)) + 
  geom_line(aes(color = sta)) +
  facet_grid(sta ~ .) 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  

# 3.0 print the fill stations  
gage_fill <- gage_fill %>% 
  arrange(sta_pair) 

print(gage_fill$sta_pair) 

# 3.1 prepare to plot the fill stations  
#gage_ck2 <- gage_dv %>% 
#  filter( 
#         sta == "lcr_bel" |          # run 01 
#         sta == "lwr_mar" |          # run 01 
#         sta == "lwr_whi" |          # run 01  
#          sta == "whi_kad" |         # run 01 
#          sta == "whi_sta"           # run 01   
#  ) %>% 
#  filter(between(water_year, yr_lag, yr_lead)) 
 
#gage_ck <- bind_rows(gage_ck, gage_ck2) 

# 3.2 plot the fill stations  
#ggplot(gage_ck, aes(date, q30_depth)) +
#  geom_line(aes(color = sta)) +
#  facet_grid(sta ~ .) 


# ~~~~~~~~ testing for issues ~~~~~~~~~~~~~~~~~~~~~~~
#test <- gage_ck %>% 
#  filter(between(water_year, 1988, 1989)) %>% 
#  filter(sta != "che_was") %>% 
#  filter(sta == "lwr_aro")  
  
#test2 <- test %>% 
#  filter(sta == "spr_her") %>% 
#  group_by(sta, water_year) %>% 
#  summarise(count = n()) 

#ggplot(test, aes(date, q1_depth)) +
##  geom_line(aes(color = sta)) +
#  facet_grid(sta ~ .) 


```

```{r prepare_for_next_Mclust_run}
# 1. check dvs for duplicates  
gage_ck <- bind_rows(gage_dv, gage_fill_dv) 
gage_ck2 <- distinct(gage_ck) 


# 2. update dvs  
gage_dv <- bind_rows(gage_dv, gage_fill_dv) %>% 
  mutate(water_year = as.integer(water_year)) %>% 
  distinct()

# 1.0 save model data 

# 1.1 save model parameters as a list 
saveRDS(params, "data/mod_params_run62")   # need to update the file
write_csv(gage_dv, "data/mod_dvs_fin")

# 1.2 use this for initial run 
#mod_clusts <- clust_sum     
#mod_sums <- mod_sum 
#mod_outputs <- output  

# 1.3 use this for runs after run 01
mod_clusts  <- bind_rows(mod_clusts, clust_sum) 
mod_sums    <- bind_rows(mod_sums, mod_sum)
mod_outputs <- bind_rows(mod_outputs, output)

# 1.4 save parameters 
write_csv(mod_clusts, "data/mod_clusts") 
write_csv(mod_sums, "data/mod_sums") 
write_csv(mod_outputs, "data/mod_outputs")

# 2. update summaries & fix gap years  
yr_sum <- gage_dv %>%                          
  group_by(sta, water_year) %>%                  
  summarise(days_yr = n()) %>%                   
  ungroup()  
 
yr_len <- yr_sum %>% 
  group_by(sta) %>% 
  summarize(min_yr = min(water_year), 
            max_yr = max(water_year), 
            yrs_record = n() + 1) %>%                   
  ungroup() %>% 
  mutate(diff_yrs = 2 + max_yr - min_yr) %>% 
  mutate(yr_gap = case_when(
    yrs_record == diff_yrs ~ "N", 
    TRUE ~ "Y"
  )) %>% 
  arrange(desc(yr_gap))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
# these change over runs - see yr_sum 
#yr_len_test01 <- yr_sum %>% 
#  filter(sta == "che_buf") %>%    
#  filter(between(water_year, 1981, 1982)) 

#yr_len_test02 <- yr_sum %>% 
#  filter(sta == "che_pla") %>%    
#  filter(between(water_year, 1980, 1981))  

#yr_len_test03 <- yr_sum %>% 
#  filter(sta == "wcc_ogl") %>%    
#  filter(between(water_year, 1980, 1981))  

#yr_len_test04 <- yr_sum %>% 
#  filter(sta == "lwr_aro") %>%    
#  filter(between(water_year, 2003, 2004))  

#yr_len_test <- bind_rows(yr_len_test01, 
 #                        yr_len_test02  
#                         yr_len_test03
#                         ) 
#View(yr_len_test)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
#yr_len <- yr_len %>% 
#  mutate(min_yr = case_when( 
#    sta == "che_buf" ~ 1982,     
#    sta == "che_pla" ~ 1983  
 #   sta == "wcc_ogl" ~ 1983, 
#    TRUE ~ min_yr 
#  )) #%>%  
 # mutate(max_yr = case_when( 
 #   sta == "lwr_aro" ~ 2003,  
#    TRUE ~ max_yr 
#  ))  


# clean up 
rm(miss_lag, miss_lead, gage_pairs, input, gage_ck, gage_ck2, mod_nm, 
   num_clust, num_obs, df,bic, loglik, X, clust_sum, cluster, mod_sum, 
   params, mod, BIC, gage_fill_dv, clust_dv, gage_fill, output, yr_len_test, 
   yr_len_test01, yr_len_test02, yr_len_test03, yr_len_test04)    
```







