---
title: "07-chap04_eco-deleted"
author: "CJ Tinant"
date: "5/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# GAM for streamflow vs. NMS axes  
```{r prepare_for_gam}

# 2 find stations for analyzing flow vs NMS axes====  
# want to check for complete stations in two groups  
sta_old <- gage_meta %>%  
  filter(min_year == 1980) %>%    
  filter(max_year >= 2001)  

sta_new <- gage_meta %>%  
  filter(min_year <  2001)  %>%   
  filter(max_year == 2018)  

# 3 drop stations with n < 20 yrs====  
#   all stations appear to have a min 20 yr record  
sta_nms <- bind_rows(sta_old, sta_new) %>%  
  distinct() %>%  
  filter(sta != "che_buf") %>%  
  filter(sta != "wcc_ogl") %>%  
  arrange(sta)  

rm(sta_new,  
   sta_old)  

# 4 get gage depths & join ecoreg data====   
gage_dep_orig   <- import("data/gage_depth.csv") %>%  
  mutate(date = ymd(Date)) %>%  
  group_by(sta, waterYear) %>%  
  mutate(count = n())  %>%  
  ungroup() %>%  
  select(-site_no)  

gage_dep_orig <- right_join(gage_dep_orig, gage_meta,  
                        by = "sta") %>%   
  select(sta,  
         date,  
         waterYear,  
         q1_depth,  
         watshed,  
         gage_group,  
         ecoreg,  
         count)  

# 5 remove incomplete years for magSeven() below====  
gage_comp <- gage_dep_orig %>%  
  filter(count > 364)  

# unit test of gage_dep==== 
gage_ck <- gage_comp %>%  
  filter(sta == "whi_sta") %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))  %>%  
  ungroup()  

# 6 filter the station data for possible nms analysis====  
gage_nms <- semi_join(gage_comp, sta_nms,  
                        by = "sta")  

# unit test of input_flow====  
# checking the length of records after removing incomplete years  
# looks at less than 20 yrs stations  
gage_ck <- gage_nms %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))  %>%  
  ungroup() %>%  
  group_by(sta) %>%  
  summarise(count = n()) %>%  
  filter(count < 20)  

# check less than 20 yr stations====  
ck_ros_ros <- gage_nms %>%  
  filter(sta == "ros_ros") %>%  
  group_by(waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))   
# ros_ros is complete 1980-1997  (not 1998)  

ck_che_pla <- gage_nms %>%    
  filter(sta == "che_pla") %>%  
  group_by(waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))   
# che_pla is complete 2001-2018  

ck_che_red <- gage_nms %>%    
  filter(sta == "che_red") %>%  
  group_by(waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))   
# che_red is complete 2000-2018  

# results -- manual -- sorry -- decided to go with 1997 split - keep ros_ros  
# start    n_init    n_fin      drop                keep           
#  1997      27       25    che_pla, che_red       ros_ros         
#  2000      28       26    ros_ros, che_pla       che_red         
#  2001      28       27      ros_ros          che_pla, che_red    

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
# ck_1997 <- sta_nms %>%  
#  select(sta) %>%  
#  filter(sta != "che_pla") %>%  
#  filter(sta != "che_red")  %>%  
#  mutate(sta_1997 = sta)  

# ck_2001 <- sta_nms %>%  
#  select(sta) %>%  
#  filter(sta != "ros_ros") %>%  
#  mutate(sta_2001 = sta)  

# gage_ck <- full_join(ck_1997, ck_2001,  
#                     by = "sta")  
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   

rm(ck_che_pla,  
   ck_che_red,  
   ck_ros_ros,  
   gage_ck)  

```

```{r 04c_final_nms_selection_1980-1997}

# 1 select stations for analyzing flow vs NMS axes====   
sta_old <- sta_nms %>%  
  filter(min_year == 1980) %>%    
  filter(max_year >= 1997) %>%   
  filter(sta != "che_pla") %>%  
  filter(sta != "che_red")  

# 4 filter the station data for nms analysis====  
gage_old <- semi_join(gage_nms, sta_old,  
                        by = "sta") %>%  
  filter(between(waterYear, 1980, 1997))   

# unit test of completeness of days & completeness of years  
# should be zero for both indicating 365 days & 18 years  
gage_ck1 <- gage_old %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup() %>%  
  arrange(count)  

gage_ck2 <- gage_ck1 %>%  
  group_by(sta) %>%  
  summarise(count = n()) %>%  
  ungroup()  

gage_ck1 <- gage_ck1 %>%   
  filter(count < 365)  

gage_ck2 <- gage_ck2 %>%   
  filter(count < 18)  

```

```{r 04d_final_nms_selection_1998-2018}

rm(gage_ck1,  
   gage_ck2)  

# 1 select stations for analyzing flow vs NMS axes====  
sta_new <- sta_nms %>%  
  filter(min_year <  1997)  %>%   
  filter(max_year == 2018) %>%  
  filter(sta != "che_pla") %>%  
  filter(sta != "che_red")  

# 4 filter the station data for nms analysis====  
gage_new <- semi_join(gage_nms, sta_new,  
                        by = "sta") %>%  
  filter(between(waterYear, 1998, 2018))   

# unit test of completeness of days & completeness of years  
# should be zero for both indicating 365 days & 18 years  
gage_ck1 <- gage_new %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup() %>%  
  arrange(count)  

gage_ck2 <- gage_ck1 %>%  
  group_by(sta) %>%  
  summarise(count = n()) %>%  
  ungroup()  

gage_ck1 <- gage_ck1 %>%   
  filter(count < 365)  

gage_ck2 <- gage_ck2 %>%   
  filter(count < 21)  

# this is the unit test that was fixed above with blp_bel_fill  
gage_ck1 <- gage_nms %>%  
  filter(sta == "blp_bel") %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

gage_ck2 <- gage_nms %>%  
  filter(sta == "hat_edg") %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  %>%  
  ungroup()   

gage_ck <- full_join(gage_ck1, gage_ck2, 
                     by = "waterYear")  # identified 2017 as the missing year  

gage_ck1 <- gage_nms %>%  
  filter(sta == "blp_bel") %>%  
  filter(waterYear == 2017) %>% 
  select(sta, date)  

gage_ck2 <- gage_nms %>%  
  filter(sta == "hat_edg") %>%  
  filter(waterYear == 2017) %>% 
  select(sta, date)   

# proof the missing date is fixed is that n = 0  
gage_ck <- full_join(gage_ck1, gage_ck2,   
                     by = "date") %>%  
  filter(is.na(sta.x))  

rm(gage_ck,   
   gage_ck1,  
   gage_ck2)  

```

```{r 04e_calculate_magSeven_statistics-new}

# calculate the 'magnificant seven' the  
#   1st 4 L-moments, AR1, phase, and amplitude====   
magSeven_list <-  gage_new %>%  
  mutate(q1_log = log10(q1_depth)) %>%  
  select(date, q1_log, sta) %>%  
  as.data.frame() %>%  
  split(.$sta) %>%  
  map(calc_magnifSeven) 

# extract elements -- not sure how to extract this better...====  
magSeven_bad_fpi <- pluck(magSeven_list, "bad_fpi") %>%   
  mutate(sta = "bad_fpi")  

magSeven_bat_bhr <- pluck(magSeven_list, "bat_bhr") %>%  
  mutate(sta = "bat_bhr")  

magSeven_bat_her <- pluck(magSeven_list, "bat_her") %>%  
  mutate(sta = "bat_her")  

magSeven_bev_pri <- pluck(magSeven_list, "bev_pri") %>%  
  mutate(sta = "bev_pri")  

magSeven_blc_wan <- pluck(magSeven_list, "blc_wan") %>%  
  mutate(sta = "blc_wan")  

magSeven_blp_bel <- pluck(magSeven_list, "blp_bel") %>%  
  mutate(sta = "blp_bel")  

magSeven_brsf_co <- pluck(magSeven_list, "brsf_co") %>%  
  mutate(sta = "brsf_co")  

magSeven_che_was <- pluck(magSeven_list, "che_was") %>%  
  mutate(sta = "che_was")  

magSeven_elk_elm <- pluck(magSeven_list, "elk_elm") %>%  
  mutate(sta = "elk_elm")  

magSeven_frn_fai <- pluck(magSeven_list, "frn_fai") %>%  
  mutate(sta = "frn_fai")  

magSeven_hat_edg <- pluck(magSeven_list, "hat_edg") %>%  
  mutate(sta = "hat_edg")  

magSeven_hor_oel <- pluck(magSeven_list, "hor_oel") %>%  
  mutate(sta = "hor_oel")  

magSeven_key_key <- pluck(magSeven_list, "key_key") %>%  
  mutate(sta = "key_key")  

magSeven_key_wew <- pluck(magSeven_list, "key_wew") %>%  
  mutate(sta = "key_wew")  

magSeven_lon_riv <- pluck(magSeven_list, "lon_riv") %>%  
  mutate(sta = "lon_riv")  

magSeven_lwr_mar <- pluck(magSeven_list, "lwr_mar") %>%  
  mutate(sta = "lwr_mar")  

magSeven_lwr_vet <- pluck(magSeven_list, "lwr_vet") %>%  
  mutate(sta = "lwr_vet")  

magSeven_lwr_whi <- pluck(magSeven_list, "lwr_whi") %>%  
  mutate(sta = "lwr_whi")  

magSeven_nio_spa <- pluck(magSeven_list, "nio_spa") %>%  
  mutate(sta = "nio_spa")  

magSeven_whi_kad <- pluck(magSeven_list, "whi_kad") %>%  
  mutate(sta = "whi_kad")  

magSeven_whi_oac <- pluck(magSeven_list, "whi_oac") %>%  
  mutate(sta = "whi_oac")  

magSeven_whi_ogl <- pluck(magSeven_list, "whi_ogl") %>%  
  mutate(sta = "whi_ogl")  

magSeven_whi_sta <- pluck(magSeven_list, "whi_sta") %>%   
  mutate(sta = "whi_sta")  

# bind rows====  
magSeven_new <- bind_rows(magSeven_bad_fpi,  
                          magSeven_bat_bhr,  
                          magSeven_bat_her,  
                          magSeven_bev_pri,  
                          magSeven_blc_wan,  
                          magSeven_blp_bel,   
                          magSeven_brsf_co,   
                          magSeven_che_was,  
                          magSeven_elk_elm,  
                          magSeven_frn_fai,  
                          magSeven_hat_edg,  
                          magSeven_hor_oel,  
                          magSeven_key_key,  
                          magSeven_key_wew,  
                          magSeven_lon_riv,  
                          magSeven_lwr_mar,  
                          magSeven_lwr_vet,  
                          magSeven_lwr_whi,  
                          magSeven_nio_spa,  
                          magSeven_whi_kad,  
                          magSeven_whi_oac,  
                          magSeven_whi_ogl,  
                          magSeven_whi_sta) 

# clean up====  
rm(magSeven_bad_fpi,  
   magSeven_bat_bhr,  
   magSeven_bat_her,  
   magSeven_bev_pri,  
   magSeven_blc_wan,  
   magSeven_blp_bel,   
   magSeven_brsf_co,   
   magSeven_che_was,  
   magSeven_elk_elm,  
   magSeven_frn_fai,  
   magSeven_hat_edg,  
   magSeven_hor_oel,  
   magSeven_key_key,  
   magSeven_key_wew,  
   magSeven_lon_riv,  
   magSeven_lwr_mar,  
   magSeven_lwr_vet,  
   magSeven_lwr_whi,  
   magSeven_nio_spa,  
   magSeven_whi_kad,  
   magSeven_whi_oac,  
   magSeven_whi_ogl,  
   magSeven_whi_sta,  
   magSeven_list)  

magSeven_new <- magSeven_new %>%  
  group_by(sta) %>%  
#  select(sta, indice, statistic) %>%  
#  unite("sta_indice", sta:indice, remove = TRUE) %>% 
  pivot_wider(  
    names_from = indice,  
    values_from = statistic)  




```

```{r test}
data_scores_new  <- semi_join(data_scores, sta_new,  
                              by = "sta")   

data_scores_new <- full_join(data_scores_new, magSeven_new,  
                             by = "sta")   

data_scores_plains <- data_scores_new %>%  
  filter(gage_group != "Black Hills Plateau")

lm_1c <- gam(lam1 ~ NMDS2,  
             data = data_scores_new)  

lm_2c <- gam(lam1 ~ NMDS1 + gage_group, 
             data = data_scores_new)  

lm_3c <- gam(lam1 ~ s(NMDS1) + NMDS2, 
             data = data_scores_new)  

lm_4c <- gam(lam1 ~ NMDS1 + NMDS2 + gage_group, 
             data = data_scores_plains)  

lm_1d <- gam(lam1 ~ NMDS2,  
             data = data_scores_plains)  

lm_2d <- gam(lam1 ~ NMDS1 + gage_group, 
             data = data_scores_plains)  

lm_3d <- gam(lam1 ~ NMDS1 + NMDS2, 
             data = data_scores_plains)  

lm_4d <- gam(lam1 ~ NMDS1 + NMDS2 + gage_group, 
             data = data_scores_plains)  

lm_1a <- lm(lam1 ~ NMDS2,  
             data = data_scores_new)  

lm_2a <- lm(lam1 ~ NMDS1 + gage_group, 
             data = data_scores_new)  

lm_3a <- lm(lam1 ~ NMDS1 + NMDS2, 
             data = data_scores_new)  

lm_4a <- lm(lam1 ~ NMDS1 + NMDS2 + gage_group, 
             data = data_scores_plains)  

lm_1b <- lm(lam1 ~ NMDS2,  
             data = data_scores_plains)  

lm_2b <- lm(lam1 ~ NMDS1 + gage_group, 
             data = data_scores_plains)  

lm_3b <- lm(lam1 ~ NMDS1 + NMDS2, 
             data = data_scores_plains)  

lm_4b <- lm(lam1 ~ NMDS1 + NMDS2 + gage_group, 
             data = data_scores_plains)  

lm_3c 
glance(lm_1a)  # 15.4  
glance(lm_2a)  
glance(lm_3a)  
glance(lm_4a)  

glance(lm_1b)  # 14.2  
glance(lm_2b)  
glance(lm_3b)  
glance(lm_4b)  

glance(lm_1c)  
glance(lm_2c)  
glance(lm_3c)  
glance(lm_4c)  

glance(lm_1d)  # 14.2   
glance(lm_2d)  
glance(lm_3d)  
glance(lm_4d)  
summary(lm_3c)  

test2 <- augment(lm_3c, data = data_scores_new) %>%  
  mutate(fitted2 = exp(.fitted))  

```


```{r plot_ordination_with-chulls}

plot_ord <- ggplot(data = data_scores_new,  
       aes(x = NMDS1, y = NMDS2)) +  
# plot the sites     
  geom_point(data = data_scores,  
             size = 3,  
             alpha = 0.7,   
             aes(colour = gage_group)   
#            shape  = gage_group  
             ) +  
# plot the convex hulls   
  stat_chull(fill = NA,  
             alpha = 0.7,  
             aes(colour = gage_group)   
             ) +  
  scale_color_discrete(guide = guide_legend())  +  
 # add the variable labels   
  geom_text(data = species_scores,  
            aes(x = NMDS1, y = NMDS2,  
                label = value),  
            alpha = 0.5,  
            size = 3) +            # add the species labels  
# add the labels for the sites  
  geom_text_repel(data = data_scores,  
            aes(x = NMDS1, y = NMDS2,  
                label = sta),  
            size  = 2,  
            vjust = 1) +  
  scale_x_reverse() +                # shows hills to plains  
# add the title and axes labels   
  labs(title = "",  
       tag = "A")  +  
  xlab("NMS1") +  
  ylab("NMS2") +  
#  coord_equal(expand = FALSE) +  
  theme_classic()  +  
  theme(legend.position =  "bottom") +  
guides(color = guide_legend(title = "", nrow = 2))   

plot_ord  

```

```{r}
ggplot(test2, aes(NMDS2, lam1)) + 
  geom_point() +  
  geom_smooth(method =  gam)
```

```{r 04c_Mclust--blp_bel92-18}

# 1 make clustering inputs, find BIC and run Mclust====         
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>% 
  filter(.class == 2) %>%   # this is the blp_bel group  
  select(-c(.class, .uncertainty))

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results----    
# nearest neighbor for blp_bel is whi_int - but no new info;  
#   next closest is whi_kad  

# * clean up global environment   
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)   

```

```{r 04d_add_best-fit_to--blp_bel92-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "blp_bel"  
sta_fr <- "whi_kad"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = "White River Badlands")  

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n())  

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n())  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to)   

```

```{r 04e_calculate_magSeven_statistics--blc_wan95-18}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...   

# 1    prepare EflowStats Input  -- for blc_wan95-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1994-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth,  
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_whi <- magSev_out %>%  
  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_whi_whi,  
                    mag_wcc_wok,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lcr_abv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19,  
            indice20)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:nio_spa) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_whi_whi,  
   mag_wcc_wok,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lcr_abv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   magSev_out,  
   magSev_in,  
   magSev_sta)  

```

```{r 4f_Mclust--blc_wan95-18}

# 1 make clustering inputs, find BIC and run Mclust====       
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====   
mclust_input <- mclust_aug %>%  
  filter(.class == 1) %>%   # this is the blc_wan group  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results----  
# nearest neighbor for blc_wan is key_wew - which is complete  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4d_add_best-fit_to--blc_wan95-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "blc_wan"  
sta_fr <- "key_wew"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4h_calculate_magSeven_statistics--ros_ros88-04}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for ros_ros88-04====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1988-10-01"),  
                 as.Date("1997-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, gage_group, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====  
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====  
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====  
#magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
#  filter(sta == "whi_int") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_int <- magSev_out %>%  
#  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====  
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====  
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====  
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====  
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====  
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wcc_wok,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lcr_abv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:nio_spa) %>%  
  spread(indice, variable)  

# * clean up global environment====  
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wcc_wok,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lcr_abv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   magSev_out,  
   magSev_in)  

```

```{r 4i_Mclust--ros_ros88-04}

# 1 make clustering inputs, find BIC and run Mclust====        
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)  

# 2 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 3 make clustering inputs, find BIC and run Mclust====  
mclust_input <- mclust_aug %>%  
  filter(between(lam1, 100, 200)) %>%      # keep nearby magnitude lam1  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====   
mclust_input <- mclust_aug %>%  
  filter(.class != 2 &  
         .class != 3) %>%   # this is the blc_wan group  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 6 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",   
#           pointsize = 1.5, palette = "jco")  

# results----  
# nearest neighbor for ros_ros is lwr_ros -- BUT need to filter by lam1  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4j_add_best-fit_to--ros_ros88-04}

# 1 subset 'to' and 'from' gages   
sta_to <- "ros_ros"  
sta_fr <- "lwr_ros"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "Lit White"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4k_calculate_magSeven_statistics--whi_int04-18}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_int04-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("2003-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "wcc_ogl") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_wcc_ogl <- magSev_out %>%  
#  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_slm") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_slm <- magSev_out %>%  
#  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_whi <- magSev_out %>%  
  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "wkc_wok") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_wcc_wok <- magSev_out %>%  
#  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "lwr_aro") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_lwr_aro <- magSev_out %>%  
#  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_sta,  
                    mag_whi_whi) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:whi_whi) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   mag_ros_ros,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_sta,  
   mag_whi_whi,  
   magSev_in,  
   magSev_sta)  

```

```{r 4l_Mclust--whi_int04-18}

# 1 make clustering inputs, find BIC and run Mclust====   
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 2 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 3 make clustering inputs, find BIC and run Mclust====          
mclust_input <- mclust_aug %>%  
  filter(between(lam1, 30, 70)) %>%      # keep nearby magnitude lam1  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")   

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for whi_int is whi_kad - WY1990-2018  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4m_add_best-fit_to--whi_int04-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "whi_int"  
sta_fr <- "whi_kad"  
Ecoreg <- "White River Badlands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4n_calculate_magSeven_statistics--wcc_ogl-88-98}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for wcc_ogl-88-98====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1987-10-01"),  
                 as.Date("1998-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wkc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_mar,  
                    mag_lwr_aro,  
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wkc_wok) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:wkc_wok) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_mar,  
   mag_lwr_aro,  
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wkc_wok,  
   magSev_in,  
   magSev_sta,  
   magSev_out)  

```

```{r 4o_Mclust--wcc_ogl-88-98}

# 1 make clustering inputs, find BIC and run Mclust====         
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 remake clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>%  
  filter(lam1 < 50) %>%   
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for wcc_ogl is whi_sta - WY1988-2018  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)   

```

```{r 4p_add_best-fit_to--wcc_ogl-88-98}

# 1 subset 'to' and 'from' gages   
sta_to <- "wcc_ogl"  
sta_fr <- "whi_sta"  
Ecoreg <- "Pine Ridge Escarpment"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  
# note: the 364 days for wcc_ogl is ok because not keeping prior 1988  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)   

```

```{r 4q_calculate_magSeven_statistics--wkc_wok-93-97}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_sta89-18====     
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1992-10-01"),  
                 as.Date("1997-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wkc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,  
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wkc_wok) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:wkc_wok) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,  
   mag_nio_spa,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wkc_wok,  
   magSev_in,  
   magSev_sta,  
   magSev_out)   

```

```{r 4r_Mclust--wkc_wok-93-97}

# 1 make clustering inputs, find BIC and run Mclust====    
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 remake clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>% 
  filter(between(lam1, 50, 130)) %>%   
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 5 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 6 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for wkc_wok is key_key    

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4s_add_best-fit_to--wkc_wok-93-97}

# 1 subset 'to' and 'from' gages   
sta_to <- "wkc_wok"  
sta_fr <- "key_key"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4t_calculate_magSeven_statistics--che_red}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_sta89-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1999-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth,  
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, gage_group, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg == "Pierre Shale Plains") %>%  
  filter(gage_group != "Pierre Shale Low") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- bat_bhr====   
magSev_out <- magSev_in %>%  
  filter(sta == "bat_bhr") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_bat_bhr <- magSev_out %>%  
  rename(bat_bhr = statistic)  

# 2.2  calculate magnificant seven -- che_buf====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_buf") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_buf <- magSev_out %>%  
  rename(che_buf = statistic)  

# 2.3  calculate magnificant seven -- che_pla====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_pla") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_pla <- magSev_out %>%  
  rename(che_pla = statistic)  

# 2.4  calculate magnificant seven -- che_red====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_red") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_red <- magSev_out %>%  
  rename(che_red = statistic)  

# 2.5  calculate magnificant seven -- che_sce====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_sce") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_sce <- magSev_out %>%  
  rename(che_sce = statistic)  

# 2.6  calculate magnificant seven -- che_was====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_was") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_was <- magSev_out %>%  
  rename(che_was = statistic)  

# 2.7  calculate magnificant seven -- whi_oac====   
magSev_out <- magSev_in %>%  
  filter(sta == "whi_oac") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_oac <- magSev_out %>%  
  rename(whi_oac = statistic)  

# 3    join magnificant seven and transpose matrix====   
magSev <- bind_cols(mag_bat_bhr,   
                    mag_che_buf,  
                    mag_che_pla,  
                    mag_che_red,  
                    mag_che_sce,  
                    mag_che_was,  
                    mag_whi_oac) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6)) %>%  
  # transpose the matrix  
  gather(sta, variable, bat_bhr:whi_oac) %>%  
  spread(indice, variable)  

# results----  
# the closest lam1 is downstream che_buf ~ but not extra data,  
#   so che_sce ~ also not extra data, so che_was  

# * clean up global environment====    
rm(mag_bat_bhr,   
   mag_che_buf,  
   mag_che_pla,  
   mag_che_red,  
   mag_che_sce,  
   mag_che_was,  
   mag_whi_oac,  
   magSev_in,  
   magSev_sta,  
   magSev_out)  

```

```{r 4u_add_best-fit_to--che-red}

# 1 subset 'to' and 'from' gages   
sta_to <- "che_red"  
sta_fr <- "che_was"  
Ecoreg <- "Pierre Shale Plains"  
Watshd <- "Cheyenne"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd,  
   magSev)   

```

```{r 4v_subset_final_records}

gage_dep_fin <- semi_join(gage_dep, ref_gage, 
                          by = "sta") %>%  
  filter(between(date,  
                 as.Date("1988-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() 

gage_check <- gage_dep_fin %>%  
  group_by(waterYear, sta) %>%  
  summarise(count = n())   

# * clean up global environment  
rm(gage_check,  
   gage_dep_orig,  
   gage_dep)   

```

## exploratory clustering -- reference gages
```{r 02a_Mclust-model_bhp}

# 1 make clustering inputs       
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a bhplat group from list based (mostly) on high slope  
grp_bhp <- mclust_aug %>%  
  filter(.class == 2) %>%  
  mutate(class = "BH Plateau") %>%  
  filter(ecoreg == "Black Hills Plateau")   

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_bhp,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_bhp,  
                       by = "sta")  

```

```{r 02b_Mclust-model_chey}

# 1 make clustering inputs      
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a Cheyenne River gages from list  
grp_che <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "Cheyenne River")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_che,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_che,  
                       by = "sta")  

```

```{r 02c_Mclust-model_sndK}

# 1 make clustering inputs   
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust====    
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model====    
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 Create a SH Keya group from list  
grp_sndK <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "SH Keya")  

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_sndK,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_sndK,  
                       by = "sta")  

```

```{r 02e_Mclust-model_sndV}

# 1 make initial clustering inputs====        
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create White River upper group 
grp_sndV <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "Sandhills Vetal")  

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_sndV,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_sndV,  
                       by = "sta")  

```

```{r 02d_Mclust-model_whrL}

# 1 make initial clustering inputs====        
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a White Clay group from list  
grp_whrL <- mclust_aug %>%  
  filter(.class == 1) %>%  
  mutate(class = "White River")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_whrL,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_whrL,  
                       by = "sta")  

```

```{r 02f_Mclust-model_wcc}

# 1 make initial clustering inputs====         
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create Keya Paha group  
grp_wcc <- mclust_aug %>%  
  filter(.class == 4) %>%  
  mutate(class = "White Clay Creek")  

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_wcc,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_wcc,  
                       by = "sta")  

```

```{r 02g_Mclust-model_whrU} 

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%   
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a white river upper group  
grp_whrU <- mclust_aug %>%  
  filter(.class == 4) %>%  
  mutate(class = "White River Upper")  

# 6 update list of gages  
mclust_in <- anti_join(mclust_in, grp_whrU,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_whrU,  
                       by = "sta")  

```

```{r 02h_Mclust-model_tablelands}

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%   
  select(-c(sta:gage_group)) # get rid of cat data    

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)   

mod <- Mclust(clust_input, x = BIC)    

# 3 get Mclust model results and tidy the Mclust model   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)    
mclust_means <- tidy(mod)    

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a Tablelands group  
grp_tab <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "Tablelands")  

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_tab,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_tab,  
                       by = "sta")  

```

```{r 02i_Mclust-model_sndL}

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust 
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 4 remove Piere Shale Low gages from list  
grp_psL <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "Pierre Shale Low")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_psL,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_psL,  
                       by = "sta")  

```

```{r 02j_Mclust-model_blc}

# 1 make initial clustering inputs====        
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 5 create a Badlands Lower group  
grp_badL <- mclust_aug %>%  
  filter(.class == 3) %>%  
  mutate(class = "Badlands Lower")  

# 6 update list  
mclust_in <- anti_join(mclust_in, grp_badL,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_badL,  
                       by = "sta")  

```

```{r 02k_Mclust-model_sndL}

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 4 create Wounded Knee gage group  
grp_sndL <- mclust_aug %>%  
  filter(.class == 5 |  
         .class == 6 |  
         .class == 7) %>%  
  mutate(class = "Sand Hills LaCreek")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_sndL,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_sndL,  
                       by = "sta")  
```

```{r 02l_Mclust-model_blc}

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 4 create Wounded Knee gage group  
grp_blc <- mclust_aug %>%  
  filter(.class == 2) %>%  
  mutate(class = "Bear Lodge")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_blc,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_blc,  
                       by = "sta")  
```

```{r 02l_Mclust-model_blc}

# 1 make initial clustering inputs====       
clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust  
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
fviz_mclust(mod, "classification", geom = "point",  
            pointsize = 1.5, palette = "jco")  

# 4 create Wounded Knee gage group  
grp_blc <- mclust_aug %>%  
  filter(.class == 2) %>%  
  mutate(class = "Bear Lodge")  

# 5 update list  
mclust_in <- anti_join(mclust_in, grp_blc,  
                       by = "sta")  

mclust_input <- anti_join(mclust_input, grp_blc,  
                       by = "sta")  
```


## final clusters -- reference gages  
<!-- 
Create final clusters with a goal of grouping ungaged catchments with  
nearest neighbors.  
-->  

```{r 03a_Mclust-final_badlands}

# 1 bind the badlands values for reclustering====   
grp_badlands <- bind_rows(grp_bad,  
                          grp_whrl,  
                          grp_whru)  %>%  
  select(class, everything()) %>%   
  select(-c(.class, .uncertainty))   

# 2 make final clustering inputs, find BIC and run Mclust====       
mclust_input <- grp_badlands  

clust_input <- mclust_input %>%  
  select(-c(class:gage_group)) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 5 make final choices====    
grp_badlands <- mclust_aug %>%  
  filter(watshed == "White Riv") %>%    
  mutate(gage = case_when(  
    .class == 1 ~ "blc_wan",  
    .class == 2 ~ "blp_bel",  
    sta == "WHR4" ~ "whi_kad",  
    sta == "WHR5" ~ "whi_int",  
    sta == "WHR3" ~ "whi_int",  
    sta == "WHR2" ~ "whi_ogl",      
    sta == "WHR1" ~ "whi_sta"))  %>%  
  filter(!is.na(gage))   

# * clean up global values  
rm(grp_bad,  
   grp_whrl,  
   grp_whru)  

```

```{r 03b_Mclust-final_cheyenne}

grp_che <- grp_che %>%  
  mutate(gage = case_when(  
    type == 'ungaged' ~ "che_red")) %>%  
  filter(!is.na(gage))  

```

```{r 03c_Mclust-final_sand-hills1}

# 1 bind the sandhills observations for reclustering====   
grp_sndhil <- bind_rows(grp_snd1,  
                        grp_snd2,  
                        grp_sndV) %>%  
  select(class, gage_group, everything()) %>%   
  select(-c(.class, .uncertainty))    

# 2 make final clustering inputs, find BIC and run Mclust====       
mclust_input <- grp_sndhil  

clust_input <- mclust_input %>%  
  select(-c(class:watshed)) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 5 final choices for sandhills and outliers====    
grp_sndhil <- mclust_aug %>%  
  mutate(gage = case_when(  
    .class == 3 ~ "lwr_mar",  
    .class == 8 ~ "lwr_mar",  
    .class == 9 ~ "lwr_mar",  
    .class == 4 ~ "lwr_vet")) %>%  
    filter(!is.na(gage))  

rm(grp_snd1,  
   grp_snd2,  
   grp_sndV)  

```

```{r 03d_Mclust-final_wok}

grp_wok <- grp_wok %>%  
  mutate(gage = case_when(  
    type == 'ungaged' ~ "wkc_wok")) %>%  
  filter(!is.na(gage))  

```

```{r 03e_Mclust-final_wcc_&_blc}

#  it's difficult to identify the remaining values; so reshuffling gaged and 
#  remaining ungaged values and reclassifying   

# 1 split data into selected and unselected====   
grp_selected <- bind_rows(grp_badlands,  
                          grp_che,  
                          grp_sndhil,  
                          grp_wok) %>%  
  filter(type == "ungaged")  

grp_unselected <- anti_join(mclust_input_all, grp_selected,  
                            by = "sta")  

# 2 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_unselected  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 3 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 6 final choices for upper White River tributary sites  ====    
grp_uppr_tribs <- mclust_aug %>%  
  mutate(gage = case_when(  
    .class == 3 ~ "blc_wan",  
    .class == 8 ~ "wcc_ogl")) %>%  
  filter(!is.na(gage))  

# 7 prepare to look at some sandhills stations by themselves====   
grp_sndhil <- mclust_aug %>%  
  filter(.class == 6)  

# * clean up global environment  
rm(grp_badlands,  
   grp_che,  
   grp_wok)  

```

```{r 03f_add_Mclust_sand-hills2}

# 1 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything())  %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 final choices for sandhills====    
grp_sndhil <- mclust_aug %>%  
  mutate(gage = case_when(  
    sta == "LWR3" ~ "lwr_mar",  
    sta == "LWR4" ~ "lwr_vet")) %>%   
  filter(!is.na(gage))  

# * clean up global environment  
rm(grp_bhp, 
   grp_kpt,  
   grp_kpt1,  
   grp_kpt2,  
   grp_med,  
   grp_out,  
   grp_psh,  
   grp_psh1,  
   grp_psl)  

```

```{r 03g_check_Mclust-vals1}

#  it's difficult to identify the remaining values, so reshuffling  
#  gaged and remaining ungaged values and reclassifying   

# 1 split data into selected and unselected====   
grp_selected <- bind_rows(grp_selected,  
                          grp_uppr_tribs,  
                          grp_sndhil) %>%  
  filter(type == "ungaged")  

grp_unselected <- anti_join(mclust_input_all, grp_selected,  
                            by = "sta")  

# 2 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_unselected  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 3 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 6 redo some sandhills fringe stations by themselves====   
grp_sndhil <- mclust_aug %>%  
  filter(.class == 7)  

# * clean up global environment  
rm(grp_uppr_tribs)  

```

```{r 03h_add_Mclust_sand-hills_fringe}

# 1 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything()) %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 5 final choices for sandhills and outliers====    
grp_med_tribs <- mclust_aug %>%  
  mutate(gage = case_when(  
    sta == "LOD1" ~ "wkc_wok",  
    sta == "CRA1" ~ "wkc_wok")) %>%    
  filter(!is.na(gage))   

```

```{r 03i_check_Mclust-vals2}

#   it's difficult to identify the remaining values, so reshuffling  
#   the gaged and remaining ungaged values and reclassifying   

# 1 split data into selected and unselected====   
grp_selected <- bind_rows(grp_selected,  
                          grp_med_tribs) %>%  
  filter(type == "ungaged")  

grp_unselected <- anti_join(mclust_input_all, grp_selected,  
                            by = "sta") %>%  
  filter(watshed != "Bad River") %>%  
  filter(watshed != "Cheyenne") %>%  
  filter(watshed != "Niobrara")   

# 2 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_unselected  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 3 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 6 redo some badlands & sandhills fringe stations by themselves  
grp_badl <- mclust_aug %>%  
  filter(.class == 1)  

grp_sndhil <- mclust_aug %>%  
  filter(.class == 2)  

rm(grp_med_tribs)  

```

```{r 03j_add_Mclust_final_badlands_fringe}

# 1 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_badl  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything())  %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 5 final choices for badlands fringe====    
grp_badl <- mclust_aug %>%  
  mutate(gage = case_when(  
    sta == "PAS2" ~ "blc_wan")) %>%   
  filter(!is.na(gage))  

```

```{r 03k_check_Mclust-vals3}

#   it's difficult to identify the remaining values, so reshuffling  
#   the gaged and remaining ungaged values and reclassifying   

# 1 split data into selected and unselected====   
grp_selected <- bind_rows(grp_selected,  
                          grp_badl) %>%  
  filter(type == "ungaged")  

# 2 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil %>%  
  select(-c(.class, .uncertainty))  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 3 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 6 redo some sandhills fringe stations by themselves  
grp_sndhil <- mclust_aug %>%  
  filter(.class == 4)  

# * clean up global environment  
rm(grp_badl)  

```

```{r 03l_add_Mclust_sand-hills_fringe}

# 1 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything()) %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 2 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 5 drop furthest out station  
grp_sndhil <- mclust_aug %>%  
  filter(.class != 1)  

# 6 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything()) %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 7 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 8 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 9 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 10 drop furthest out station  
grp_sndhil <- mclust_aug %>%  
  filter(.class != 2)  

# 11 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything()) %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 12 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 13 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 14 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 15 drop furthest out station  
grp_sndhil <- mclust_aug %>%  
  filter(.class != 2)  

# 16 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_sndhil  

mclust_in <- mclust_input %>%  
  select(sta:watshed, gage_group, everything()) %>%  
  select(-c(.class:.uncertainty))  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 17 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 18 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 19 quick visual results====  
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 20 final choices for badlands fringe====    
grp_sndhil <- mclust_aug %>%  
  mutate(gage = case_when(  
    .class == "1" ~ "ros_ros")) %>%   
  filter(!is.na(gage))  

``` 

```{r 03m_add-Mclust_keya-final}

#   it's difficult to identify the remaining values, so reshuffling  
#   the gaged and remaining ungaged values and reclassifying   

# 1 split data into selected and unselected  
grp_selected <- bind_rows(grp_selected,  
                          grp_sndhil) %>%  
  filter(type == "ungaged")  

grp_unselected <- anti_join(mclust_input_all, grp_selected,  
                            by = "sta")  

# 2 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_unselected  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 3 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 6 redo some badlands & sandhills fringe stations by themselves  
grp_keya <- mclust_aug %>%  
  filter(.class == 8 |  
         .class == 3)  

# 7 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_keya %>%  
  select(-c(.class, .uncertainty))  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 8 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 9 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 10 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 11 filter to get stations by themselves  
grp_keya <- mclust_aug %>%  
  filter(.class != "4" &  
         .class != "5")  

# 12 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_keya %>%  
  select(-c(.class, .uncertainty))  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 8 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 9 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 10 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 11 filter to get stations by themselves  
grp_keya <- mclust_aug %>%  
  filter(.class != "2" &  
         .class != "3" &  
         .class != "4" &  
         .class != "6")   

# 12 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_keya %>%  
  select(-c(.class, .uncertainty))  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 13 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 14 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 15 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 16 filter to get stations by themselves  
grp_keya <- mclust_aug %>%  
  filter(.class != "1")   

# 17 standardize data for mclust & make final clustering inputs====     
mclust_input <- grp_keya %>% 
  select(-c(.class, .uncertainty))  

mclust_in <- mclust_input %>%  
  mutate_if(is.numeric, scale) %>%  
  select(sta:watshed, gage_group, everything())  

clust_input <- mclust_in  %>%  
  select(-c(sta:gage_group)) # get rid of cat data   

# 18 find Bayesian Information Criterion and run Mclust====   
BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 19 get Mclust model results and tidy the Mclust model====   
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 20 quick visual results====   
#fviz_mclust(mod, "classification", geom = "point",  
#            pointsize = 1.5, palette = "jco")  

# 21 choose final locations  
grp_keya <- mclust_aug %>%  
  mutate(gage = "wkc_wok") %>%   
  filter(!is.na(gage))  

# 22 add keya paha to selected gages & rename unselected as gaged====   
grp_selected <- bind_rows(grp_selected,  
                          grp_keya) %>%  
  filter(type == "ungaged")  

grp_gaged <- grp_unselected %>%  
  filter(type == "gaged")  

# * clean up global environment  
rm(clust_input,  
   grp_keya,  
   grp_sndhil,  
   grp_unselected,  
   mclust_aug,  
   mclust_fit,  
   mclust_in,  
   mclust_in_all, 
   mclust_input, 
   mclust_input_all,  
   mclust_means,  
   mod,  
   BIC)  

```

# fill missing data  
```{r 04a_import_munge_data_for_stats}     

# 1 import gage metadata & join ecoreg data====   
gage_meta <- import("data/gage_meta.csv") %>%  
  select(sta,  
         years_rec:apparent_yrs,  
         dec_lat_va,  
         dec_long_va)  

gage_eco <- wsd_summary %>%  
  select(sta, ecoreg) %>%  
  filter(ecoreg != "")  

gage_meta <- right_join(gage_meta, gage_eco,  
                        by = "sta")  

# 2 get gage depts & join ecoreg data====   
gage_dep_orig   <- import("data/gage_depth.csv") %>%  
  mutate(date = ymd(Date)) %>%  
  group_by(sta, waterYear) %>%  
  mutate(count = n())  %>%  
  ungroup() %>%  
  select(-site_no)  

gage_dep_orig <- right_join(gage_dep_orig, grp_gaged,  
                        by = "sta") %>%   
  select(sta,  
         date,  
         waterYear,  
         q1_depth,  
         watshed,  
         gage_group,  
         ecoreg,  
         count)  

# 3 need to remove incomplete years for magSeven() below  
gage_dep <- gage_dep_orig %>%  
  filter(count > 364)  

# 4 prepare ungaged and reference gage dfs====   
grp_selected <- grp_selected %>%  
  select(sta, gage)  

ref_gage <- grp_selected %>%  
  select(gage) %>%  
  distinct()  

ref_gage <- semi_join(gage_meta, ref_gage,  
                  by = c("sta" = "gage")) %>%  
  rename(dec_lat = dec_lat_va) %>%  
  rename(dec_lon = dec_long_va)  

# 5 find gages to fill incomplete reference gage====   
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# taking a look at ref_gage -- there's 13 gages representing the 45 ungaged  
# EMAP stations.    
#   Cheyenne River stas (n = 2) are represented by che_red -- WY 2000-2018  
#   Sandhills stations (n = 6) are represented by lwr_mar & lwr_vet --  
#       lwr_mar & lwr_vet are complete for the period of record.  
#   Tertiary stations (n = 37) are represented by 10 stations  
#       the longest incomplete station is whi_sta -- WY 1988-2018  
#   We are going to use this period of record for SSI calculations  
#   the next shortest record is:   
#         blp_bel -- WY 1992-2018 -> fit with whi_kad,  
#   then, blc_wan -- WY 1995-2018 -> fit with key_wew,  
#   then, ros_ros -- WY 1980-2004 -> fit with lwr_ros,  
#   then, whi_int -- WY 2004-2018 -> fit with blp_bel,  
#   then, wcc_ogl -- WY 1988-1998 -> fit with whi_sta,  
#   then, wkc_wok -- WY 1992-1997 -> fit with wcc_ogl  

gage_check <- gage_dep %>%  
  filter(sta == "whi_sta") %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n(),  
            min = min(date),  
            max = max(date))  %>%  
  ungroup()  

```

```{r 04b_calculate_magSeven_statistics--blp_bel92-18}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'    
# Should get below into a purrr loop, but...   

# 1    prepare EflowStats Input  -- for whi_sta89-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1992-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, gage_group, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_whi <- magSev_out %>%  
  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_whi_whi,  
                    mag_wcc_wok,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lcr_abv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19,  
            indice20)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:nio_spa) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_whi_whi,  
   mag_wcc_wok,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lcr_abv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   magSev_in,  
   magSev_sta,  
   magSev_out,  
   gage_eco)   

```

```{r 04c_Mclust--blp_bel92-18}

# 1 make clustering inputs, find BIC and run Mclust====         
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>% 
  filter(.class == 2) %>%   # this is the blp_bel group  
  select(-c(.class, .uncertainty))

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results----    
# nearest neighbor for blp_bel is whi_int - but no new info;  
#   next closest is whi_kad  

# * clean up global environment   
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)   

```

```{r 04d_add_best-fit_to--blp_bel92-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "blp_bel"  
sta_fr <- "whi_kad"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = "White River Badlands")  

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n())  

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n())  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to)   

```

```{r 04e_calculate_magSeven_statistics--blc_wan95-18}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...   

# 1    prepare EflowStats Input  -- for blc_wan95-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1994-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth,  
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_whi <- magSev_out %>%  
  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_whi_whi,  
                    mag_wcc_wok,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lcr_abv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19,  
            indice20)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:nio_spa) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_whi_whi,  
   mag_wcc_wok,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lcr_abv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   magSev_out,  
   magSev_in,  
   magSev_sta)  

```

```{r 4f_Mclust--blc_wan95-18}

# 1 make clustering inputs, find BIC and run Mclust====       
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====   
mclust_input <- mclust_aug %>%  
  filter(.class == 1) %>%   # this is the blc_wan group  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results----  
# nearest neighbor for blc_wan is key_wew - which is complete  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4d_add_best-fit_to--blc_wan95-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "blc_wan"  
sta_fr <- "key_wew"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4h_calculate_magSeven_statistics--ros_ros88-04}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for ros_ros88-04====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1988-10-01"),  
                 as.Date("1997-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, gage_group, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====  
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====  
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====  
#magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
#  filter(sta == "whi_int") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_int <- magSev_out %>%  
#  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====  
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====  
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====  
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====  
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====  
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====  
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====  
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wcc_wok,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lcr_abv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:nio_spa) %>%  
  spread(indice, variable)  

# * clean up global environment====  
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wcc_wok,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lcr_abv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   magSev_out,  
   magSev_in)  

```

```{r 4i_Mclust--ros_ros88-04}

# 1 make clustering inputs, find BIC and run Mclust====        
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)  

# 2 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 3 make clustering inputs, find BIC and run Mclust====  
mclust_input <- mclust_aug %>%  
  filter(between(lam1, 100, 200)) %>%      # keep nearby magnitude lam1  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 5 make clustering inputs, find BIC and run Mclust====   
mclust_input <- mclust_aug %>%  
  filter(.class != 2 &  
         .class != 3) %>%   # this is the blc_wan group  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 6 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",   
#           pointsize = 1.5, palette = "jco")  

# results----  
# nearest neighbor for ros_ros is lwr_ros -- BUT need to filter by lam1  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4j_add_best-fit_to--ros_ros88-04}

# 1 subset 'to' and 'from' gages   
sta_to <- "ros_ros"  
sta_fr <- "lwr_ros"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "Lit White"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4k_calculate_magSeven_statistics--whi_int04-18}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_int04-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("2003-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "wcc_ogl") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_wcc_ogl <- magSev_out %>%  
#  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_slm") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_slm <- magSev_out %>%  
#  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_whi <- magSev_out %>%  
  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "wkc_wok") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_wcc_wok <- magSev_out %>%  
#  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "lwr_aro") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_lwr_aro <- magSev_out %>%  
#  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_sta,  
                    mag_whi_whi) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:whi_whi) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   mag_ros_ros,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_sta,  
   mag_whi_whi,  
   magSev_in,  
   magSev_sta)  

```

```{r 4l_Mclust--whi_int04-18}

# 1 make clustering inputs, find BIC and run Mclust====   
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 2 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 3 make clustering inputs, find BIC and run Mclust====          
mclust_input <- mclust_aug %>%  
  filter(between(lam1, 30, 70)) %>%      # keep nearby magnitude lam1  
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 4 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")   

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for whi_int is whi_kad - WY1990-2018  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4m_add_best-fit_to--whi_int04-18}

# 1 subset 'to' and 'from' gages   
sta_to <- "whi_int"  
sta_fr <- "whi_kad"  
Ecoreg <- "White River Badlands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4n_calculate_magSeven_statistics--wcc_ogl-88-98}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for wcc_ogl-88-98====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1987-10-01"),  
                 as.Date("1998-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wkc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_mar,  
                    mag_lwr_aro,  
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,   
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wkc_wok) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:wkc_wok) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_mar,  
   mag_lwr_aro,  
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,   
   mag_nio_spa,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wkc_wok,  
   magSev_in,  
   magSev_sta,  
   magSev_out)  

```

```{r 4o_Mclust--wcc_ogl-88-98}

# 1 make clustering inputs, find BIC and run Mclust====         
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 remake clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>%  
  filter(lam1 < 50) %>%   
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for wcc_ogl is whi_sta - WY1988-2018  

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)   

```

```{r 4p_add_best-fit_to--wcc_ogl-88-98}

# 1 subset 'to' and 'from' gages   
sta_to <- "wcc_ogl"  
sta_fr <- "whi_sta"  
Ecoreg <- "Pine Ridge Escarpment"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  
# note: the 364 days for wcc_ogl is ok because not keeping prior 1988  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)   

```

```{r 4q_calculate_magSeven_statistics--wkc_wok-93-97}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_sta89-18====     
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1992-10-01"),  
                 as.Date("1997-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth, 
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg != "Pierre Shale Plains" &  
         ecoreg != "Black Hills Plateau") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- blc_wan====    
magSev_out <- magSev_in %>%  
  filter(sta == "blc_wan") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_blc_wan <- magSev_out %>%  
  rename(blc_wan = statistic)  

# 2.2  calculate magnificant seven -- blp_bel====    
magSev_out <- magSev_in %>%  
  filter(sta == "blp_bel") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_blp_bel <- magSev_out %>%  
  rename(blp_bel = statistic)  

# 2.3  calculate magnificant seven -- key_key====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_key") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_key <- magSev_out %>%  
  rename(key_key = statistic)  

# 2.4  calculate magnificant seven -- key_wew====    
magSev_out <- magSev_in %>%  
  filter(sta == "key_wew") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_key_wew <- magSev_out %>%  
  rename(key_wew = statistic)  

# 2.5  calculate magnificant seven -- ros_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "ros_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_ros_ros <- magSev_out %>%  
  rename(ros_ros = statistic)  

# 2.6  calculate magnificant seven -- wcc_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "wcc_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wcc_ogl <- magSev_out %>%  
  rename(wcc_ogl = statistic)  

# 2.7  calculate magnificant seven -- whi_int====    
magSev_out <- magSev_in %>%     # doesn't intersect with WY 1992-1997  
  filter(sta == "whi_int") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_int <- magSev_out %>%  
  rename(whi_int = statistic)  

# 2.8  calculate magnificant seven -- whi_kad====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_kad") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_kad <- magSev_out %>%  
  rename(whi_kad = statistic)  

# 2.9  calculate magnificant seven -- whi_ogl====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_ogl") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_ogl <- magSev_out %>%  
  rename(whi_ogl = statistic)  

# 2.10 calculate magnificant seven -- whi_slm====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_slm") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_slm <- magSev_out %>%  
  rename(whi_slm = statistic)  

# 2.11 calculate magnificant seven -- whi_sta====    
magSev_out <- magSev_in %>%  
  filter(sta == "whi_sta") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_sta <- magSev_out %>%  
  rename(whi_sta = statistic)  

# 2.12 calculate magnificant seven -- whi_whi====    
#magSev_out <- magSev_in %>%  
#  filter(sta == "whi_whi") %>%  
#  select(-c(sta, gage_group, ecoreg)) %>%   
#  calc_magnifSeven()  

#mag_whi_whi <- magSev_out %>%  
#  rename(whi_whi = statistic)  

# 2.13 calculate magnificant seven -- wkc_wok====    
magSev_out <- magSev_in %>%  
  filter(sta == "wkc_wok") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_wkc_wok <- magSev_out %>%  
  rename(wkc_wok = statistic)  

# 2.14 calculate magnificant seven -- lon_riv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lon_riv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lon_riv <- magSev_out %>%  
  rename(lon_riv = statistic)  

# 2.15 calculate magnificant seven -- lwr_aro====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_aro") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_aro <- magSev_out %>%  
  rename(lwr_aro = statistic)  

# 2.16 calculate magnificant seven -- lcr_abv====    
magSev_out <- magSev_in %>%  
  filter(sta == "lcr_abv") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lcr_abv <- magSev_out %>%  
  rename(lcr_abv = statistic)  

# 2.17 calculate magnificant seven -- lwr_mar====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_mar") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_mar <- magSev_out %>%  
  rename(lwr_mar = statistic)  

# 2.18 calculate magnificant seven -- lwr_ros====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_ros") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_ros <- magSev_out %>%  
  rename(lwr_ros = statistic)  

# 2.19 calculate magnificant seven -- lwr_vet====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_vet") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_vet <- magSev_out %>%  
  rename(lwr_vet = statistic)  

# 2.20 calculate magnificant seven -- lwr_whi====    
magSev_out <- magSev_in %>%  
  filter(sta == "lwr_whi") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_lwr_whi <- magSev_out %>%  
  rename(lwr_whi = statistic)  

# 2.21 calculate magnificant seven -- nio_spa====    
magSev_out <- magSev_in %>%  
  filter(sta == "nio_spa") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_nio_spa <- magSev_out %>%  
  rename(nio_spa = statistic)  

# 3    join magnificant seven and transpose matrix====    
magSev <- bind_cols(mag_blc_wan,  
                    mag_blp_bel,  
                    mag_key_key,  
                    mag_key_wew,  
                    mag_lcr_abv,  
                    mag_lon_riv,  
                    mag_lwr_aro,  
                    mag_lwr_mar,   
                    mag_lwr_ros,   
                    mag_lwr_vet,   
                    mag_lwr_whi,  
                    mag_nio_spa,  
                    mag_ros_ros,  
                    mag_wcc_ogl,  
                    mag_whi_int,  
                    mag_whi_kad,  
                    mag_whi_ogl,  
                    mag_whi_slm,  
                    mag_whi_sta,  
                    mag_wkc_wok) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6,  
            indice7,  
            indice8,  
            indice9,  
            indice10,  
            indice11,  
            indice12,  
            indice13,  
            indice14,  
            indice15,  
            indice16,  
            indice17,  
            indice18,  
            indice19)) %>%  
  # transpose the matrix  
  gather(sta, variable, blc_wan:wkc_wok) %>%  
  spread(indice, variable)  

# * clean up global environment====    
rm(mag_blc_wan,  
   mag_blp_bel,  
   mag_key_key,  
   mag_key_wew,  
   mag_lcr_abv,  
   mag_lon_riv,  
   mag_lwr_aro,  
   mag_lwr_mar,   
   mag_lwr_ros,   
   mag_lwr_vet,   
   mag_lwr_whi,  
   mag_nio_spa,  
   mag_ros_ros,  
   mag_wcc_ogl,  
   mag_whi_int,  
   mag_whi_kad,  
   mag_whi_ogl,  
   mag_whi_slm,  
   mag_whi_sta,  
   mag_wkc_wok,  
   magSev_in,  
   magSev_sta,  
   magSev_out)   

```

```{r 4r_Mclust--wkc_wok-93-97}

# 1 make clustering inputs, find BIC and run Mclust====    
mclust_input <- magSev  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 3 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 4 remake clustering inputs, find BIC and run Mclust====         
mclust_input <- mclust_aug %>% 
  filter(between(lam1, 50, 130)) %>%   
  select(-c(.class, .uncertainty))  

clust_input <- mclust_input %>%  
  select(-sta) # get rid of cat data   

BIC <- mclustBIC(clust_input, verbose = FALSE)  

mod <- Mclust(clust_input, x = BIC)   

# 5 get Mclust model results and tidy the Mclust model  
mclust_fit <-glance(mod)  
mclust_aug <- augment(mod, mclust_input)   
mclust_means <- tidy(mod)  

# 6 quick visual results  
#fviz_mclust(mod, "classification", geom = "point",  
#           pointsize = 1.5, palette = "jco")  

# results ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
# nearest neighbor for wkc_wok is key_key    

# * clean up global environment  
rm(magSev,  
   clust_input,  
   mclust_aug,  
   mclust_fit,  
   mclust_input,  
   mclust_means,  
   mod,  
   BIC)  

```

```{r 4s_add_best-fit_to--wkc_wok-93-97}

# 1 subset 'to' and 'from' gages   
sta_to <- "wkc_wok"  
sta_fr <- "key_key"  
Ecoreg <- "Keya Paha Tablelands"  
Watshd <- "White Riv"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd)  

```

```{r 4t_calculate_magSeven_statistics--che_red}

# group stations by the first 4 L-moments, AR1, phase, and amplitude aka  
#  the 'magnificant seven'   
# Should get below into a purrr loop, but...  

# 1    prepare EflowStats Input  -- for whi_sta89-18====    
magSev_in <- gage_dep %>%  
  filter(between(date,  
                 as.Date("1999-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() %>%  
  select(sta,  
         date,  
         discharge = q1_depth,  
         gage_group,  
         ecoreg)  

magSev_sta <- magSev_in %>%  
  select(sta, gage_group, ecoreg) %>%  
  distinct() %>%  
  filter(ecoreg == "Pierre Shale Plains") %>%  
  filter(gage_group != "Pierre Shale Low") %>%  
  arrange(sta)  

# 2.1  calculate magnificant seven -- bat_bhr====   
magSev_out <- magSev_in %>%  
  filter(sta == "bat_bhr") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%  
  calc_magnifSeven()  

mag_bat_bhr <- magSev_out %>%  
  rename(bat_bhr = statistic)  

# 2.2  calculate magnificant seven -- che_buf====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_buf") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_buf <- magSev_out %>%  
  rename(che_buf = statistic)  

# 2.3  calculate magnificant seven -- che_pla====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_pla") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_pla <- magSev_out %>%  
  rename(che_pla = statistic)  

# 2.4  calculate magnificant seven -- che_red====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_red") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_red <- magSev_out %>%  
  rename(che_red = statistic)  

# 2.5  calculate magnificant seven -- che_sce====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_sce") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_sce <- magSev_out %>%  
  rename(che_sce = statistic)  

# 2.6  calculate magnificant seven -- che_was====   
magSev_out <- magSev_in %>%  
  filter(sta == "che_was") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_che_was <- magSev_out %>%  
  rename(che_was = statistic)  

# 2.7  calculate magnificant seven -- whi_oac====   
magSev_out <- magSev_in %>%  
  filter(sta == "whi_oac") %>%  
  select(-c(sta, gage_group, ecoreg)) %>%   
  calc_magnifSeven()  

mag_whi_oac <- magSev_out %>%  
  rename(whi_oac = statistic)  

# 3    join magnificant seven and transpose matrix====   
magSev <- bind_cols(mag_bat_bhr,   
                    mag_che_buf,  
                    mag_che_pla,  
                    mag_che_red,  
                    mag_che_sce,  
                    mag_che_was,  
                    mag_whi_oac) %>%  
  # drop the duplicate indices  
  select(-c(indice1,  
            indice2,  
            indice3,  
            indice4,  
            indice5,  
            indice6)) %>%  
  # transpose the matrix  
  gather(sta, variable, bat_bhr:whi_oac) %>%  
  spread(indice, variable)  

# results----  
# the closest lam1 is downstream che_buf ~ but not extra data,  
#   so che_sce ~ also not extra data, so che_was  

# * clean up global environment====    
rm(mag_bat_bhr,   
   mag_che_buf,  
   mag_che_pla,  
   mag_che_red,  
   mag_che_sce,  
   mag_che_was,  
   mag_whi_oac,  
   magSev_in,  
   magSev_sta,  
   magSev_out)  

```

```{r 4u_add_best-fit_to--che-red}

# 1 subset 'to' and 'from' gages   
sta_to <- "che_red"  
sta_fr <- "che_was"  
Ecoreg <- "Pierre Shale Plains"  
Watshd <- "Cheyenne"  

gage_to <- gage_dep %>%  
  filter(sta %in% sta_to)  

gage_from <- gage_dep %>%  
  filter(sta %in% sta_fr) %>%  
  mutate(sta = sta_to) %>%  
  mutate(ecoreg = Ecoreg) %>%  
  mutate(watshed = Watshd)   

# 2 add any incomplete years  
gage_poss <- gage_dep_orig %>%  
  filter(sta %in% sta_to)  

gage_to <- bind_rows(gage_poss, gage_to) %>%  
  distinct()  

# 2 make distinct records, check, join, and double-check   
gage_check <- gage_to %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()   

gage_from <- anti_join(gage_from, gage_to,  
                        by = "date")  

gage_mixed <- bind_rows(gage_from, gage_to)  

gage_check <- gage_mixed %>%  
  group_by(sta, watshed, ecoreg, waterYear) %>%  
  summarise(count = n()) %>%  
  ungroup()  

# 3 add records to 'gage_dep' and check  
gage_dep <- bind_rows(gage_mixed, gage_dep) %>%  
  distinct()  

gage_check <- gage_dep %>%  
  group_by(sta, waterYear) %>%  
  summarise(count = n())  

# * clean up global environment   
rm(gage_from,  
   gage_mixed,  
   gage_poss,  
   gage_to,  
   sta_fr,  
   sta_to,  
   Ecoreg,  
   Watshd,  
   magSev)   

```

```{r 4v_subset_final_records}

gage_dep_fin <- semi_join(gage_dep, ref_gage, 
                          by = "sta") %>%  
  filter(between(date,  
                 as.Date("1988-10-01"),  
                 as.Date("2018-09-30"))) %>%  
  as.data.frame() 

gage_check <- gage_dep_fin %>%  
  group_by(waterYear, sta) %>%  
  summarise(count = n())   

# * clean up global environment  
rm(gage_check,  
   gage_dep_orig,  
   gage_dep)   

```


```{r mclust_cont}

# 5 create hydrologic clusters====   
mclust_aug %<>%  
  # create a short name variable for ecoregion  
  mutate(ecoreg2 = case_when(  
    ecoreg == "Pierre Shale Plains" ~ "psp",  
    ecoreg == "Keya Paha Tablelands" ~ "kpt",  
    ecoreg == "Pine Ridge Escarpment" ~ "pre",  
    ecoreg == "Black Hills Plateau" ~ "bhp",  
    ecoreg == "Sand Hills" ~ "snd",  
    ecoreg == "White River Badlands" ~ "bad")) %>%  
  # unite ecoregion and Mclust groups  
  unite("hydro_group", ecoreg2, group,  
        sep = "_",  
        remove = FALSE) %>%  
  # create hydrologic groups based on MCLUST  
  mutate(hydro_mclust = case_when(  
    hydro_group == "bad_2" ~ "Tertiary Clays",  
    hydro_group == "pre_2" ~ "Tertiary Clays",  
    hydro_group == "bhp_3" ~ "Black Hills Plateau",  
    hydro_group == "kpt_3" ~ "Keya Paha Tablelands",  
    hydro_group == "kpt_4" ~ "Keya Paha Tablelands",  
    hydro_group == "snd_3" ~ "Sand Hills",  
    hydro_group == "snd_4" ~ "Sand Hills",  
    hydro_group == "snd_1" ~ "GW Control",  
    hydro_group == "bhp_1" ~ "GW Control",   
    L1           < 1.0     ~ "Pierre Shale Low",  
    L1           > 1.0     ~ "Pierre Shale High",  
    TRUE ~ "NA")) %>%  
  # change hydro_group based on STL decomp (below)  
  mutate(hydro_group = case_when(  
    sta == "fal_hot" ~ "GW Control",  
    TRUE ~ hydro_mclust)) %>%  
  # relevel ecoregion for plotting  
  mutate(ecoreg = factor(ecoreg)) %>%  
  mutate(ecoreg = fct_relevel(ecoreg,  
                              "Pierre Shale Plains",  
                              "Pine Ridge Escarpment",  
                              "White River Badlands",  
                              "Black Hills Plateau",  
                              "Keya Paha Tablelands",  
                              "Sand Hills")) %>%  
  # relevel hydrologic groups for plotting  
  mutate(hydro_group = factor(hydro_group)) %>%  
  mutate(hydro_group = fct_relevel(hydro_group,  
                                   "Pierre Shale Low",  
                                   "Pierre Shale High",  
                                   "Tertiary Clays",  
                                   "Black Hills Plateau",  
                                   "Keya Paha Tablelands",  
                                   "GW Control",  
                                   "Sand Hills"))   

# 6 create hydrologic group summaries====   
hydro_group <- mclust_aug %>%  
  # summarise by hydrologic group  
  group_by(hydro_group) %>%  
  summarise(L1 = mean(L1),   
            L_CV = mean(L_CV),  
            L_skew = mean(L_skew),  
            L_kurtosis = mean(L_kurtosis)) %>%  
  ungroup() %>%  
  mutate_if(is.numeric, round, 2) %>%  
  # add ecoregions as doubled for cases when two ecoregions are present  
  mutate(ecoreg = case_when(  
    hydro_group == "GW Control" ~  
      "Black Hills Plateau_Sand Hills",  
    hydro_group == "Tertiary Clays" ~  
      "Pine Ridge Escarpment_White River Badlands",  
    hydro_group == "Pierre Shale High" ~  
      "Pierre Shale Plains_Pierre Shale Plains",  
    hydro_group == "Black Hills Plateau" ~  
      "Black Hills Plateau_Black Hills Plateau",  
    hydro_group == "Keya Paha Tablelands" ~  
      "Keya Paha Tablelands_Keya Paha Tablelands",   
    hydro_group == "Sand Hills" ~  
      "Sand Hills_Sand Hills",  
    hydro_group == "Pierre Shale Low" ~  
      "Pierre Shale Plains_Pierre Shale Plains")) %>%  
  # separate ecoregons into two columns  
  separate(ecoreg, c("ecoreg1", "ecoreg2"), sep = "_") %>%  
  # gather and drop duplicates  
  gather(key = drop, val = ecoreg,  
         -c(hydro_group, L1, L_CV, L_skew, L_kurtosis)) %>%  
  select(-drop) %>%  
  distinct() %>%  
  arrange(L_skew) %>%   
  # relevel ecoregion for plotting  
  mutate(ecoreg = factor(ecoreg)) %>% 
  mutate(ecoreg = fct_relevel(ecoreg,  
                              "Pierre Shale Plains",  
                              "Pine Ridge Escarpment",  
                              "White River Badlands",  
                              "Black Hills Plateau",  
                              "Keya Paha Tablelands",  
                              "Sand Hills")) %>%  
  # relevel hydrologic groups for plotting  
  mutate(hydro_group = factor(hydro_group)) %>% 
  mutate(hydro_group = fct_relevel(hydro_group,  
                                   "Pierre Shale Low",  
                                   "Pierre Shale High",  
                                   "Tertiary Clays",  
                                   "Black Hills Plateau",  
                                   "GW Control",  
                                   "Keya Paha Tablelands", 
                                   "Sand Hills"))  

# 7 export results and clean up global environment====   
export(mclust_aug, "data/lmom_mclust_fit.csv")  

rm(lmom_data,  
   clust_input,  
   mod,  
   BIC,  
   mclust_fit,  
   mclust_means,  
   lmom_gage)  

```

```{r 12-Mclust-plot}  

# plot intitial Mclust groups ====    
mclust_aug %>%  
  ggplot(aes(L_skew, L_kurtosis)) +  
  # set theme, facets, labels #  
  theme_bw() +  
  facet_wrap(vars(ecoreg)) +  
  ggtitle("Initial L-moment groups for streamflow gages",  
          subtitle = "scaled by L1 magnitude") +  
  xlab("L-skew") +  
  ylab("L-kurtosis") +  
  # plot stations #  
  geom_point(aes(color = group,  
                 shape = CV_group,  
                 size = L1)) +  
  # set the plot styles #  
  scale_size(range = c(1, 4), guide = "none") +     
  scale_color_grey(name = "Mclust group") +  
  scale_shape(name = "CV magnitude")  

# plot final hydrologic groups====   
mclust_aug %>%  
  ggplot(aes(L_skew, L_kurtosis)) +  
  # set theme, facets, labels #  
  theme_bw() +  
  #  ggtitle("Hydrologic groups based on streamflow gage L-moments",  
  #          subtitle = "Scaled by L1 magnitude") +  
  xlab("L-skew") +  
  ylab("L-kurtosis") +  
  theme_bw() +  
  facet_wrap(vars(hydro_group)) +  
  # plot stations #  
  geom_point(aes(color = ecoreg,  
                 size = L1,  
                 shape = CV_group)) +  
  # set the legend names #  
  scale_size(range = c(1, 4), guide = "none") +     
  scale_color_grey(name = "Ecoregion") +  
  scale_shape(name = "L-CV magnitude")  

# save individual plot - drop this to add stuff below   
ggsave("figure/Mclust_lmoms.png",  
       units = "in",  
       width = 7,  
       height = 4.5)  

rm(mclust_plot)  

```

```{r 13 export_mclust-table}

# 1  arrange gage data====    
mclust_aug <- mclust_aug %>%  
  select(sta,  
         ecoreg,  
         L1:L_kurtosis,  
         hydro_group) %>%  
  arrange(hydro_group, ecoreg)  

# 2  prepare export table====   
# 3  set the numeric columns====    
col_key_num <- mclust_aug %>%   
  names()  

# 4  convert tibble to a flextable====      
coef_table <- mclust_aug %>%   
  # convert factors to characters   
  mutate(hydro_group = as.character(hydro_group)) %>%  
  mutate(ecoreg = as.character(ecoreg)) %>%  
  # create flextable object  
  flextable() %>%   
  colformat_num(col_keys = col_key_num,   
                big.mark=",",   
                digits = 2, na_str = "") %>%  
  # rename header labels  
  set_header_labels(sta = "Name",    
                    ecoreg  = "Ecoregion",  
                    L_CV = "L-CV",  
                    L_skew = "L-skew",  
                    L_kurtosis = "L-kurtosis",  
                    hydro_group = "Hydrologic group") %>%    
  autofit() %>%  
  align(align = "center") %>%   # not working!!!  
  theme_booktabs()   

# 5  export a docx of flextables & clean up global environment====      
coef_table <- read_docx() %>%  
  body_add_flextable(value = coef_table)  
print(coef_table, target = "output/lmom_mclust_table.docx")   

rm(coef_table,  
   col_key_num)       

```

```{r prior}

# 2 reduce lengths for the 30-year analysis====   
#gage_meta <- import("data/gage_meta.csv") %>%  
#  select(site_no:sta,  
#         dec_lat_va,  
#         dec_long_va,  
#         drain_area_va,  
#         alt_va,  
#         contrib_drain_area_va)  
gage_mon <- gage_mon %>%  
  filter(between(Date,  
                 as.Date("1988-10-15"),  
                 as.Date("2018-09-15")))  

# * create some data checks====   
gage_check <- gage_mon %>%  
  group_by(sta) %>%  
  summarise(min = min(Date),  
            max = max(Date)  
  )  

gage_full <- gage_mon %>%  
  select(sta) %>%  
  distinct()  

# 3 add flow regime to the 30-year timeframe====   
flow_regime <-  import("data/gage_meta.csv") %>%  
  select(sta,  
         flow_regime)  

flow_regime <- semi_join(flow_regime, gage_full,  
                         by = "sta")  

# * join flow regime to streamflow data  
gage_mon <- full_join(gage_mon, flow_regime,   
                          by = "sta")  

# * check results by printing a summary of the data====   
gage_mon %>%   
  group_by(sta) %>%   
  summarise(count = n()) %>%   
  ungroup() %>%   
  mutate(num_yr = count/12)  

# 4 summarise gage ecoregion & flow regime====   
gage_summary <- gage_mon %>%  
  select(sta, ecoreg, flow_regime) %>%   
  distinct()  



```

