---
title: "Untitled"
author: "CJ Tinant"
date: "2/18/2020"
output: html_document
---


<!--  
Y = b1x + b2x2 

let x1 = normalized family differential index 
    x2 = days from June 1  
-->  

```{r setup_&_library, message=FALSE}    
  
knitr::opts_chunk$set(echo = FALSE)      
options(tibble.print_max = 70) # sets tibble output for printing          

# Sets up the library of packages====    
library("conflicted")        # An alternative conflict resolution strategy  
library("here")              # identifies where to save work  
library("rio")           # more robust I/O - to import and clean data  
library("lubridate")     # easier dates   
#library("broom")         # tidies linear models   
#library("ggbeeswarm")    # plot 1D data as a violin / beeswarm plot  
#library("scales")        # graphical scales map data to aesthetics,  
#                         #   & methods for determining breaks and labels 
                         #   for axes and legends   
#library("mclust")        # model-based clustering & density estimation  
#library("flextable")     # functions for tabular reporting  
#library("officer")       # facilitates '.docx' access for table export  
#library("patchwork")     # the 'composer of plots'  
#library("EflowStats")    # reimplementation of the Hydrologic Index Tool  
#library("factoextra")    # quickly visualize Mclust plots  
#library("SCI")           # calculates SPI & SSI   
library("janitor")  
library("tidyverse")  
  
# resolve conflicted packages====   
conflict_prefer("filter", "dplyr")  
conflict_prefer("select", "dplyr")  
conflict_prefer("as.dist", "stats")  
conflict_prefer("first", "dplyr")  
conflict_prefer("map", "purrr")  
conflict_prefer("lag", "dplyr")  

# other packages I have thought about====   
#library("rnoaa")             # R wrapper for NOAA data inc. NCDC  
#library("lmomco")        # lmoments to find distribution   
#library('deldir')        # for Vorononi tesselation - Theissen polygons  

#library("forecast")      # using the BoxCox function   
#library("anomalize")     # detect anomalies using the tidyverse   
#library("dabestr")       # data analysis using bootstrap estimation    
#library("cowplot")       # multiple plots with plot_grid()  
#library("timetk")        # tool kit for working with time series in R   
#library("tidyquant")     # integrate quant. analysis tools w/ tidyverse  
#library("corrr")         # Tidy correlation tables and correlation plotting  
#library("cranlogs")      # For inspecting package downloads over time  
# for GLMs                    
# library("doMC")          # parallelization for caret  
# library("caret")         # classification and regression training  
# library("glmnet")        # fit a GLM with lasso or elasticnet regularization  
# library("Metrics")       # evaluation metrics for machine learning  
# library("ggfortify")        # data vis tools for statistical analysis  
# library("ggpubr")           # easy ggplot wrappers for publication ready  
#                             #   'ggplot2'- based plots  
# library("standardize")      # tools for controlling continuous variable   
#  scaling and factor contrasts for linear models   
# library("pdftools")         # utilities for extracting text, fonts,  
#   attachments and metadata from a pdf file.  

# packages for spatial data====   
#library("biogeo")            # Functions for error detection & correction  
#   in point-data datasets; includes functions   
#   to parse & convert coords to decimal-degrees  
#library("maps")              # Outlines: countries, states & counties  
#library("mapdata")           # higher-resolution outlines  
#library('ggmap')             # Spatial visualization with ggplot2   
#library("sf")                # Simple features--spatial geometries for R  
#library("RColorBrewer")      # map color schemes -- http://colorbrewer2.org  
# packages for colors====   
#library("colorspace")        # Manipulate & assess colors & palettes  
#library("munsell")           # Access & manipulate munsell system colours  
#   https://github.com/cwickham/munsell  

# packages for lists and urls====   
#library("jsonlite")          # Convert between JSON data and R objects  
#library("curl")              # Drop-in replacement for base url  
#library("listviewer")        # htmlwidget for interactive views of R lists  
#library("forecast")         # for BoxCox.lambda   
#library("magrittr") # provides aliases for easier reading  
#library("workflowr") # creates a research website  
#library("bookdown") #  
#library(unpivotr) # fix nasty Excel files  
#library("friendlyeval")  
#library("mathpix")                # support for 'Mathpix' image to 'LaTeX'    
#library("grateful") - not yet ready for R 3.5.0  
#lmomco <- citation("lmomco")  
#toBibtex(lmomco)  

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
why_to_write <- function()   
{today <- today(tzone = "")  
paper3 <- ymd("2020-04-15")  
until <- paper3 - today  
print(paste("You have", until, "days until the third paper is due"))   
}   
why_to_write()  

```

```{r functions}
# 1. this function takes in a dataframe,  
#   changes names to snake_case,   
#   changes any blank character columns to NA  
#   drops the NA values   
#   drops empty columns  

clean_fun <- function(df) {  
  new_df <- clean_names(df) %>%  
  mutate_if(is.character, list(~na_if(., ""))) %>%  
    remove_empty("rows") %>%  
  select(-c(benthic_tolerance,  
            functional_feeding_designation)) %>%  
  mutate_if(is.numeric, replace_na, 0) %>%  
  mutate(sums = rowSums(select(., -c(order, family, notes))))  %>%  
  filter(sums > 0) %>%  
  mutate_if(is.numeric, na_if, 0) %>%  
  select(-sums) %>%  
  mutate(notes = as.character(notes))  
#  unite("family_notes", c(family, notes))    
  return(new_df)  
}  

count_fun <- function(df) {  
  gather(df) %>%  
  group_by(key) %>%  
  drop_na() %>%  
  summarise(count = n(),  
            sum = sum(value, na.rm = TRUE))  
}  

```

```{r import_macros}

# 1 import and clean data saved from Excel worksheets as .csv====  
#   importing from 'xlsx': 2015/04/09_OB   

AMH1_2014 <- import("data/AMH1_2014.csv") %>%  
  clean_fun()  

BEA1_2013 <- import("data/BEA1_2013.csv") %>%  
  clean_fun()  

BEA2_2013 <- import("data/BEA2_2013.csv") %>%  
  clean_fun()  

BEA3_2013 <- import("data/BEA3_2013.csv") %>%  
  clean_fun()  

BEL1_2013 <- import("data/BEL1_2013.csv") %>%  
  clean_fun()  

BEL2_2013 <- import("data/BEL2_2013.csv") %>%  
  clean_fun()  

BLP1_2013 <- import("data/BLP1_2013.csv") %>%  
  clean_fun()  

BUZ1_2013 <- import("data/BUZ1_2013.csv") %>%  
  clean_fun()  

CHE1_2011 <- import("data/CHE1_2011.csv") %>%  
  clean_fun()  

CHE2_2011 <- import("data/CHE2_2011.csv") %>%  
  clean_fun()  

COR1_2013 <- import("data/COR1_2013.csv") %>%  
  clean_fun()  

CRA1_2013 <- import("data/CRA1_2013.csv") %>%  
  clean_fun()  

EAN1_2013 <- import("data/EAN1_2013.csv") %>%  
  clean_fun()  

EAN2_2013 <- import("data/EAN2_2013.csv") %>%  
  clean_fun()  

LOD1_prior <- import("data/LOD1_prior2000.csv") %>%  
  clean_fun()  

LON1_2013 <- import("data/LON1_2013.csv") %>%  
  clean_fun()  

LWR1_2014 <- import("data/LWR1_2014.csv") %>%  
  clean_fun()  

LWR2_2014 <- import("data/LWR2_2014.csv") %>%  
  clean_fun()  

LWR3_2014 <- import("data/LWR3_2014.csv") %>%  
  clean_fun() %>%  
  rename(lwr2r6 = lwr3r6)  # fixed mislabled data  based on similiarity  

LWR4_2012 <- import("data/LWR4_2012.csv") %>%  
  clean_fun() 

MER1_2014 <- import("data/MER1_2014.csv") %>%  
  clean_fun()  

MER3_2014 <- import("data/MER3_2014.csv") %>%  
  clean_fun() %>%  
  rename(mer3t8 = mer4t8)  

MER4_2014 <- import("data/MER4_2014.csv") %>%  
  clean_fun()  

NFL1_2014 <- import("data/NFL1_2014.csv") %>%  
  clean_fun()  

PAS1_2013 <- import("data/PAS1_2013.csv") %>%   
  clean_fun()  

PAS2_2013 <- import("data/PAS2_2013.csv") %>%  
  clean_fun()  

PAS3_2013 <- import("data/PAS3_2013.csv") %>%  
  clean_fun()  

POR1_2012 <- import("data/POR1_2012.csv") %>%  
  clean_fun()  

POR2_2014 <- import("data/POR2_2014.csv") %>%  
  clean_fun()  

POR3_2014 <- import("data/POR3_2014.csv") %>%  
  clean_fun()  

POT1_2013 <- import("data/POT1_2013.csv") %>%  
  clean_fun()  

RED1_2014 <- import("data/RED1_2014.csv") %>%  
  clean_fun()  

WCC1_2012 <- import("data/WCC1_2012.csv") %>%  
  clean_fun()  

WCC2_2012 <- import("data/WCC2_2012.csv") %>%  
  clean_fun()  

WCC3_2012 <- import("data/WCC3_2012.csv") %>%  
  clean_fun()  

WHI1_2011 <- import("data/WHI1_2011.csv") %>%  
  clean_fun()  

WHI2_2011 <- import("data/WHI2_2011.csv") %>%  
  clean_fun()  

WHI3_2008 <- import("data/WHI3_2008.csv") %>%  
  clean_fun()  

WHI4_prior <- import("data/WHI4_prior2000.csv") %>%  
  clean_fun()  

WHI5_2013 <- import("data/WHI5_2013.csv") %>%  
  clean_fun()  

WOL1_2011 <- import("data/WOL1_2011.csv") %>%  
  clean_fun()  

WOK1_2012 <- import("data/WOK1_2012.csv") %>%  
  clean_fun()  

WOK2_2014 <- import("data/WOK2_2014.csv") %>%  
  clean_fun()  

WOK3_2012 <- import("data/WOK3_2012.csv") %>%  
  clean_fun()  

WOK4_2014 <- import("data/WOK4_2014.csv") %>%  
  clean_fun()  

```

```{r join_macros}

# join macros-post2000====  
# joins columns by putting the dfs into a list,  
#   then merging, and reducing to a dataframe  

scratch <- full_join(AMH1_2014,  
                      BEA1_2013,  
                     by = c("order", "family", "notes")) %>%  
  full_join(., BEA2_2013, by = c("order", "family", "notes")) %>%  
  full_join(., BEA3_2013, by = c("order", "family", "notes")) %>%  
  full_join(., BEL1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., BEL2_2013, by = c("order", "family", "notes")) %>%  
  full_join(., BLP1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., BUZ1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., CHE1_2011, by = c("order", "family", "notes")) %>%  
  full_join(., CHE2_2011, by = c("order", "family", "notes")) %>%  
  full_join(., COR1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., CRA1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., EAN1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., EAN2_2013, by = c("order", "family", "notes")) %>%  
  full_join(., LOD1_prior, by = c("order", "family", "notes")) %>%  
  full_join(., LON1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., LWR1_2014, by = c("order", "family", "notes")) %>%  
  full_join(., LWR2_2014, by = c("order", "family", "notes")) %>%  
  full_join(., LWR3_2014, by = c("order", "family", "notes")) %>%  
  full_join(., LWR4_2012, by = c("order", "family", "notes")) %>%  
  full_join(., MER1_2014, by = c("order", "family", "notes")) %>%  
  full_join(., MER3_2014, by = c("order", "family", "notes")) %>%  
  full_join(., MER4_2014, by = c("order", "family", "notes")) %>%  
  full_join(., NFL1_2014, by = c("order", "family", "notes")) %>%  
  full_join(., PAS1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., PAS2_2013, by = c("order", "family", "notes")) %>%  
  full_join(., PAS3_2013, by = c("order", "family", "notes")) %>%  
  full_join(., POR1_2012, by = c("order", "family", "notes")) %>%   
  full_join(., POR2_2014, by = c("order", "family", "notes")) %>%  
  full_join(., POR3_2014, by = c("order", "family", "notes")) %>%  
  full_join(., POT1_2013, by = c("order", "family", "notes")) %>%  
  full_join(., RED1_2014, by = c("order", "family", "notes")) %>%  
  full_join(., WCC1_2012, by = c("order", "family", "notes")) %>%  
  full_join(., WCC2_2012, by = c("order", "family", "notes")) %>%  
  full_join(., WCC3_2012, by = c("order", "family", "notes")) %>%  
  full_join(., WHI1_2011, by = c("order", "family", "notes")) %>%  
  full_join(., WHI2_2011, by = c("order", "family", "notes")) %>%  
  full_join(., WHI3_2008, by = c("order", "family", "notes")) %>%  
  full_join(., WHI4_prior, by = c("order", "family", "notes")) %>%  
  full_join(., WHI5_2013, by = c("order", "family", "notes")) %>%  
  full_join(., WOL1_2011, by = c("order", "family", "notes")) %>%  
  full_join(., WOK1_2012, by = c("order", "family", "notes")) %>%  
  full_join(., WOK2_2014, by = c("order", "family", "notes")) %>%  
  full_join(., WOK3_2012, by = c("order", "family", "notes")) %>%  
  full_join(., WOK4_2014, by = c("order", "family", "notes")) 

```

```{r check_count}

# check the count of the samples====  
# should be 12 samples  
count_ck <- scratch %>%  
  select(-c(order:notes)) %>%  
  count_fun() %>%  
  filter(sum < 79)  

# 2.1 check individual samples - count====  
# these are the samples identified above
check_amh1p <- scratch %>%  
  select(starts_with("amh1p")) %>%  
  count_fun()  

check_lwr2a <- scratch %>%  
  select(starts_with("lwr2a")) %>%  
  count_fun()  

check_lwr4a <- scratch %>%  
  select(starts_with("lwr4a")) %>%  
  count_fun()  

check_mer3d <- scratch %>%  
  select(starts_with("mer3d")) %>%  
  count_fun()  

check_por2a <- scratch %>%  
  select(starts_with("por2a")) %>%  
  count_fun()  

check_por1c <- scratch %>%  
  select(starts_with("por1c")) %>%  
  count_fun()  

check_red1b <- scratch %>%  
  select(starts_with("red1b")) %>%  
  count_fun()  

check_wcc2a <- scratch %>%  
  select(starts_with("wcc2a")) %>%  
  count_fun()  

check_wcc3d <- scratch %>%  
  select(starts_with("wcc3d")) %>%  
  count_fun()  

check_wdk4b <- scratch %>%  
  select(starts_with("wdk4b")) %>%  
  count_fun()  

check_wok3a <- scratch %>%  
  select(starts_with("wok3a")) %>%  
  count_fun()  

check_wtr4a <- scratch %>%  
  select(starts_with("wtr4a")) %>%  
  count_fun()  

# should be 12 count 
count_ck <- bind_rows(check_amh1p,  
                      check_lwr2a,  
                      check_lwr4a,  
                      check_mer3d,  
                      check_por1c,  
                      check_por2a,  
                      check_red1b,  
                      check_wcc2a,  
                      check_wcc3d,  
                      check_wdk4b,  
                      check_wok3a,  
                      check_wtr4a)  

rm(check_amh1p,  
   check_lwr2a,  
   check_lwr4a,  
   check_mer3d,  
   check_por1c,  
   check_por2a,  
   check_red1b,  
   check_wcc2a,  
   check_wcc3d,  
   check_wdk4b,  
   check_wok3a,   
   check_wtr4a,  
   clean_fun)   

```

```{r check_names}

# 1.0 check site names for duplicates or other errors====  
# 1.1 get sites with suffixes====   
# check_vars should be n = 13 -- but below is n = 9  
# 1   lwr1s7,  
# 2   lwr2t6 = lwr2t6,  
# 3   lwr3r6 = lwr3r6,  
# 4   me	ra7,          # didn't include -- fix name below
# 5   mer4t8 = mer4t8,  
# 6   por2d7,  
# 7   por3s6,  
# 8   wcc2a6	7,  
# 9   wok2s6,   
# 10  wok4r6  

check_vars <- scratch %>%  
  names() %>%  
  enframe(name = NULL) %>%  
  separate(value, 
           c("site", "suffix"),  
           extra = "merge") %>%  
  filter(!is.na(suffix))  

# 1.2 check individual sites====  
check_lwr1s <- scratch %>%  
  select(starts_with("lwr1s")) %>%  
  count_fun()  

check_lwr2t <- scratch %>%  
  select(starts_with("lwr2t")) %>%  
  count_fun()   

check_lwr3r <- scratch %>%  
  select(starts_with("lwr3r")) %>%  
  count_fun()   

check_mer4t8 <- scratch %>%  
  select(starts_with("mer4t8")) %>%  
  count_fun()   

check_por2d <- scratch %>%  
  select(starts_with("por2d")) %>%  
  count_fun()  

check_por3s <- scratch %>%  
  select(starts_with("por3s")) %>%  
  count_fun()  

check_wcc2a <- scratch %>%  
  select(starts_with("wcc2a")) %>%  
  count_fun()  

check_wok2s <- scratch %>%  
  select(starts_with("wok2s")) %>%  
  count_fun()  

check_wok4r <- scratch %>%  
  select(starts_with("wok4r")) %>%  
  count_fun()  

# bind rows and clean up====  
check_vars <- bind_rows(check_lwr1s,  
                        check_lwr2t,  
                        check_lwr3r,  
                        check_mer4t8,  
                        check_por2d, 
                        check_por3s,  
                        check_wcc2a,  
                        check_wok2s,  
                        check_wok4r)  

rm(check_lwr1s,  
   check_lwr2t,  
   check_lwr3r,  
   check_mer4t8,  
   check_por2d, 
   check_por3s,  
   check_wcc2a,  
   check_wok2s,  
   check_wok4r, 
   count_fun)  

```

```{r fix_names}

# from results above -- keep more diverse samples with count near 100   
scratch <- scratch %>%  
  rename(lwr1s7_dup = lwr1s7) %>%  
  rename(lwr1s7 = lwr1s7_2) %>%   
  rename(lwr2t6_dup = lwr2t6_b) %>%  
  rename(lwr2t6 = lwr2t6_a) %>%  
  rename(lwr3r6_dup = lwr3r6_2) %>%  
  rename(lwr3r6 = lwr3r6_3)  %>%  
  rename(mer3a7 = me_ra7) %>%  
  rename(por2d7_dup = por2d7_2) %>%  
  rename(por3s6_dup = por3s6) %>%  
  rename(por3s6 = por3s6_b)  

rm(AMH1_2014,  
   BEA1_2013,  
   BEA2_2013,  
   BEA3_2013,  
   BEL1_2013,  
   BEL2_2013,   
   BLP1_2013,  
   BUZ1_2013,  
   CHE1_2011,  
   CHE2_2011,  
   COR1_2013,  
   CRA1_2013,  
   EAN1_2013,  
   EAN2_2013,  
   LOD1_prior,  
   LON1_2013,  
   LWR1_2014,  
   LWR2_2014,  
   LWR3_2014,  
   LWR4_2012,  
   MER1_2014,  
   MER3_2014,  
   MER4_2014,   
   NFL1_2014,  
   PAS1_2013,   
   PAS2_2013,   
   PAS3_2013,   
   POR1_2012,   
   POR2_2014,  
   POR3_2014,  
   POT1_2013,  
   RED1_2014,  
   WCC1_2012,  
   WCC2_2012,  
   WCC3_2012,  
   WHI1_2011,  
   WHI2_2011,  
   WHI3_2008,  
   WHI4_prior,  
   WHI5_2013,  
   WOL1_2011,  
   WOK1_2012,  
   WOK2_2014,  
   WOK3_2012,  
   WOK4_2014)  

```

```{r fix_taxa_names-prep}

# 1. organize taxa by taxonomy====  
#    rows are genera & cols are sites  
# 2. remove difficult characters from the data====  
#     difficut characters to work with include: '"(", ")", "*", ":"  
macros <- scratch %>%  
  rename(genus = notes) %>%  
  arrange(genus) %>%  
  mutate(genus = str_remove_all(genus, "\\(")) %>%  
  mutate(genus = str_remove_all(genus, "\\)")) %>%  
  mutate(genus = str_remove_all(genus, "\\*")) %>%  
  mutate(genus = str_remove_all(genus, "\\:"))  

# 3.1 split data into genus and no genus groups====  
macros_noGen <- macros %>%  
  filter(is.na(genus))  

# 3.2 clean non-year specific genera====  
macros_Gen <- macros %>%  
  filter(!is.na(genus)) %>%  
  mutate(genus = case_when(  
    str_detect(genus, "Acerpenna sp.") ~ "Acerpenna spp",  
    str_detect(genus, "Ambrysus sp.") ~ "Ambrysus spp",  
    str_detect(genus, "Chrysops sp.") ~ "Chrysops spp",  
    str_detect(genus, "^Culicoides sp.") ~ "Culicoides spp",  
    str_detect(genus, "^Dicranota sp.") ~ "Dicranota spp",  
    str_detect(genus, "Class Arachnida; Eylaoidea sp.") ~ "Eylaoidea spp",  
    str_detect(genus, "Class Gastropoda; Ferrissia sp.") ~ "Ferrissia spp",  
    str_detect(genus, "Assumed same values as Elmidae") ~ "NA",  
    str_detect(genus, "Adult") ~ "NA",  
    str_detect(genus, "2 adults included in this count") ~ "NA",  
    str_detect(genus, "2011 -1 pupae") ~ "NA",  
    str_detect(genus, "3 pupa") ~ "NA",  
    str_detect(genus, "4 adults in 2011") ~ "NA",  
    str_detect(genus, "4 Pupae 2012") ~ "NA",  
    str_detect(genus, "Class Bivalvia formerly Pelecypoda") ~ "NA",  
    str_detect(genus, "Class Arachnida") ~ "NA",  
    str_detect(genus, "ClassArachnida") ~ "NA",    
    str_detect(genus, "Crawdad marked on datasheet") ~ "NA",  
    str_detect(genus, "Class Gastropoda") ~ "NA",  
    str_detect(genus, "Variable") ~ "NA",  
    str_detect(genus, "Extremely rare") ~ "NA",  
    str_detect(genus, "^Ferrissia sp.") ~ "Ferrissia spp", 
    str_detect(genus, "^From") ~ "NA",  
    str_detect(genus, "^from") ~ "NA", 
    str_detect(genus, "Larval; adults excluded") ~ "NA",  
    str_detect(genus, "^Lebertia sp.") ~ "Lebertia spp", 
    str_detect(genus, "Microcylloepus sp.") ~ "Microcylloepus spp", 
    str_detect(genus, "^Nectopsyche sp.") ~ "Nectopsyche spp",  
    str_detect(genus, "Ochrotichia sp.") ~ "Ochrotichia spp", 
    str_detect(genus, "^ONE PUPA") ~ "NA",  
    str_detect(genus, "Paraleptophlebia sp.") ~ "Paraleptophlebia spp", 
    str_detect(genus, "Procloeon sp.") ~ "Procloeon spp",  
    str_detect(genus, "Sp = Ephoron") ~ "Ephoron spp",  
    str_detect(genus, "Stenelmis sp.") ~ "Stenelmis spp",  
    str_detect(genus, "Tolerance unknown") ~ "NA",  
    str_detect(genus, "undetermaned tolerence") ~ "NA",  
    str_detect(genus, "Undetermined") ~ "NA",  
    str_detect(genus, "U") ~ "NA",  
    str_detect(genus, "Undetermined Tolerance") ~ "NA",  
    str_detect(genus, "Undetermined tolerance values") ~ "NA",  
    str_detect(genus, "Undetermined values") ~ "NA",  
    str_detect(genus, "Tanypodinae sp.") ~ "Tanypodinae spp",  
    TRUE ~ genus)) %>%  
    na_if("NA")  

# data check----  
# macros is length 259 & macros_Gen + macros_noGen is length 259  

# 3.3 clean non-year specific genera cont.====   
macros_Gen <- macros_Gen %>%  
  mutate(scratch = case_when(  
    genus == "Acerpenna spp" ~ "y",  
    genus == "Ambrysus spp" ~ "y",  
    genus == "Chrysops spp" ~ "y",  
    genus == "Eylaoidea spp"~ "y",  
    genus == "Ferrissia spp" ~ "y",  
    genus == "Culicoides spp" ~ "y",  
    genus == "Dicranota spp" ~ "y",  
    genus == "Lebertia spp" ~ "y",  
    genus == "Microcylloepus spp" ~ "y",  
    genus == "Nectopsyche spp" ~ "y",  
    genus == "Ochrotichia spp" ~ "y",  
    genus == "Paraleptophlebia spp" ~ "y",  
    genus == "Procloeon spp" ~ "y",  
    genus == "Ephoron spp "~ "y",  
    genus == "Stenelmis spp" ~ "y",  
    genus == "Tanypodinae spp" ~ "y",  
    is.na(genus) ~ "y",  
    TRUE ~ "n")) %>%  
  select(scratch, everything())  

# 3.4    add finished genus to other set of data genus ====
macros_GenFin <- macros_Gen %>%  
  filter(scratch == "y") %>%  
  select(-scratch)  

macros_noGen <- bind_rows(macros_noGen,  
                          macros_GenFin)  

macros_Gen <- macros_Gen %>%  
  filter(scratch == "n") %>%  
  select(-scratch)  

# data check----  
# macros is length 259 & macros_Gen + macros_noGen is length 259  
rm(macros_GenFin) 

```

```{r fix_taxa_names_genus_year_data}

# fix individual year data in genus====  
# rows are genera & columns are sites  
# purpose is to separate rows with two levels of taxonomic classification  
#   recycling scratch var from above  

# 1.1.  Procladius sp.'96====   
scratch <- macros_Gen %>%  
  filter(genus == "Procladius sp.'96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1d8" ~ "Procladius spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- scratch  

# 1.2.  Stienelmis sp. '96====  
scratch <- macros_Gen %>% 
  filter(genus == "Stienelmis sp. '96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "bea1d7" ~ "Stienelmis spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.3.  Stienelmis sp.'93====  
scratch <- macros_Gen %>% 
  filter(genus == "Stienelmis sp.'93") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1a7" ~ "Stienelmis spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.4.  Hagenius spp====  
scratch <- macros_Gen %>% 
  filter(genus == "1996 sp = hagenius") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "lwr2d7" ~ "Hagenius spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.5.  Hygrobatoidae sp.'12====  
scratch <- macros_Gen %>% 
  filter(genus == "Hygrobatoidae sp.'12") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1t8" ~ "Hygrobatoidae spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.6.  Hygrobatoidae sp.'12====  
scratch <- macros_Gen %>% 
  filter(genus == "Hygrobatoidea sp.") %>%  
  mutate(genus = "Hygrobatoidea spp")  

macros_new <- bind_rows(macros_new, scratch)  

# 1.7.  Symphitopsyche sp. '96====  
scratch <- macros_Gen %>% 
  filter(genus == "Symphitopsyche sp. '96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "bea1d7" ~ "Symphitopsyche spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.8.  Limnodrilus spp====  
scratch <- macros_Gen %>% 
  filter(genus == "Limnodrilus udekemian'94; Enchytraeidae sp.'96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1b6" ~ "Limnodrilus udekemian",  
    name == "mer1d8" ~ "Enchytraeidae sp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.9.  Naididae Family====  
scratch <- macros_Gen %>% 
  filter(genus == "Naididae Family") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(family = "Naididae") %>%  
  mutate(genus = "NA") %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.10. Polycentrous cinereus '96====  
scratch <- macros_Gen %>% 
  filter(genus == "Polycentrous cinereus '96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "bea1d7" ~ "Polycentrous cinereus",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.11. Ephoron spp====  
scratch <- macros_Gen %>% 
  filter(genus == "Ephoron spp") 

macros_new <- bind_rows(macros_new, scratch)  

# 1.12. Simulium sp.'96====  
scratch <- macros_Gen %>% 
  filter(genus == "Simulium sp.'96") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1d8" ~ "Simulium spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.13. Tipula sp.b5; Subfamily Limoniinaer6====  
scratch <- macros_Gen %>% 
  filter(genus == "Tipula sp.b5; Subfamily Limoniinaer6") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "wdk4b5" ~ "Tipula spp",  
    name == "wok4r6_7" ~ "Limoniinae",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.14. Tricorythodes sp. 1996====  
scratch <- macros_Gen %>% 
  filter(genus == "Tricorythodes sp. 1996") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "lwr4d7" ~ "Tricorythodes spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 1.15. Tipula sp.'94====  
scratch <- macros_Gen %>% 
  filter(genus == "Tipula sp.'94") %>% 
  pivot_longer(-c(order, family, genus)) %>%  
  arrange(value) %>%  
  mutate(genus = case_when(  
    name == "mer1b6" ~ "Tipula spp",  
    TRUE ~ "NA")) %>%  
  na_if("NA") %>%  
  pivot_wider()  

macros_new <- bind_rows(macros_new, scratch)  

# 2.0   join back cleaned genera====  
macros <- bind_rows(macros_new, macros_noGen)  

# data check----  
# macros is now length 273 & macros_new + macros_noGen is length 273  
# number of sites is unchanged  

rm(macros_Gen,  
   macros_new,  
   macros_noGen,  
   scratch)  

```

```{r fix_taxa_names-genus}

# looked at data to look for cases where there might be multiple genera   

macros <- macros %>%  
  mutate(genus = case_when(  
    str_detect(genus, "Enchytraeidae sp") ~ "Enchytraeidae spp",  
    str_detect(family, "Athericidae") ~ "Atherix spp",  
    str_detect(family, "Culicoides sp.") ~ "Culicoides spp",  
    str_detect(family, "Culicoides sp.") ~ "Culicoides spp",  
    str_detect(family, "Dicranota sp.") ~ "Dicranota spp",  
    str_detect(family, "Ferrissia sp.") ~ "Ferrissia spp",  
    str_detect(family, "Gammaridae") ~ "Gammarus spp",  
    str_detect(family, "Heloridae") ~ "Helorus spp",  
    str_detect(family, "Talitridae") ~ "Hyalella azteca",  
    str_detect(family, "Taltridae") ~ "Hyalella azteca",  
    str_detect(family, "Isoperla sp.") ~ "Isoperla spp",  
    str_detect(family, "Psychodidae") ~ "Pericoma spp",  
    str_detect(family, "Pisidiidae") ~ "Pisidium spp",  
    str_detect(family, "pisidiidae") ~ "Pisidium spp",  
    str_detect(family, "Potamanthus") ~ "Potamanthus spp",  
    str_detect(family, "Cossidae") ~ "Prionoxystus spp",  
    str_detect(family, "Pteronarcyidae") ~ "Pteronarcys spp",  
    str_detect(family, "Simulium sp.") ~ "Simulium spp",  
    str_detect(family, "Simulidae") ~ "Simulium spp",  
    str_detect(family, "Simuliidae") ~ "Simulium spp",  
    str_detect(family, "Elmid. Stienelmis") ~ "Stienelmis spp",  
    str_detect(family, "Heloridae") ~ "Tricorythodes spp",  
    TRUE ~ genus)) %>%  
  arrange(genus) %>%  
    na_if("NA")  

```

```{r fix_taxa_names-family}

# used internet to look up families for the general below  
macros <- macros %>%  
  mutate(family = case_when(  
    str_detect(genus, "Culicoides spp") ~ "Ceratopogonidae",   
    str_detect(genus, "Simulium spp") ~ "Simuliidae",  
    str_detect(genus, "Isoperla spp") ~ "Perlodidae",  
    str_detect(genus, "Dicranota spp") ~ "Pediciidae",  
    str_detect(family, "Ancyclidae") ~ "Planorbidae",  
    str_detect(family, "Ancylidae") ~ "Planorbidae",  
    str_detect(family, "corydalidae") ~ "Corydalidae",  
    str_detect(family, "Culcidae") ~ "Culicidae",  
    str_detect(family, "Curulionidae") ~ "Curculionidae",  
    str_detect(family, "Drysticidae") ~ "Dytiscidae",  
    str_detect(family, "Elmid. Stienelmis") ~ "Elmidae",  
    str_detect(family, "Ephyridae") ~ "Ephydridae",  
    str_detect(family, "Nematomorpha") ~ "Gordioida",  
    str_detect(family, "Hirudina") ~ "Glossiphoniidae",  
    str_detect(family, "Hirudinea") ~ "Glossiphoniidae",  
    str_detect(family, "Hirudinidea") ~ "Glossiphoniidae",  
    str_detect(family, "Hirudinidae") ~ "Glossiphoniidae",  
    str_detect(family, "hebridae") ~ "Hebridae",  
    str_detect(family, "hydracarina") ~ "Hydracarina",  
    str_detect(family, "Hydrocarina") ~ "Hydracarina",  
    str_detect(family, "Hydrobidae") ~ "Hydrobiidae",  
    str_detect(family, "Tubificidae") ~ "Naididae",  
    str_detect(family, "^Naididae") ~ "Naididae",    
    str_detect(family, "Nematoda") ~ "Nematomorpha",    
    str_detect(family, "notonectidae") ~ "Notonectidae",  
    str_detect(family, "Notonectdae") ~ "Notonectidae",  
    str_detect(family, "Ferrissia sp.") ~ "Planorbidae",  
    str_detect(family, "piscicolidae") ~ "Piscicolidae",  
    str_detect(family, "Polymitarcidae") ~ "Polymitarcyidae",  
    str_detect(family, "Polymitoreyidae") ~ "Polymitarcyidae",  
    str_detect(family, "Potamanthus") ~ "Potamanthidae",  
    str_detect(family, "Ptilodactylia") ~ "Ptilodactylidae",  
    str_detect(family, "pisidiidae") ~ "Sphaeriidae",  
    str_detect(family, "Pisidiidae") ~ "Sphaeriidae",  
    str_detect(family, "Sailidae") ~ "Sialidae",  
    str_detect(family, "Simulidae") ~ "Simuliidae",  
    str_detect(family, "Taltridae") ~ "Talitridae", 
    str_detect(family, "^Tipula sp.") ~ "Tipulidae",  
    str_detect(family, "Tupulidae") ~ "Tipulidae",  
    str_detect(family, "^Tricorythodes sp.") ~ "Tricorythodes sp.", 
    str_detect(family, "Notostraca") ~ "Triopsidae",  
    str_detect(family, "viviparidae") ~ "Viviparidae",  
    str_detect(family, "Unclassified") ~ "NA",  
    str_detect(family, "Unknown") ~ "NA",  
    str_detect(family, "needs a look") ~ "NA",  
    str_detect(order, "Conchostraca") ~ "Conchostraca",  
    str_detect(order, "Nematomorpha") ~ "Gordioida",  
    TRUE ~ family)) %>%  
  arrange(order) %>%  
    na_if("NA")    

```

```{r fix_taxa_names-order}

# used internet to look up order from families below   
macros <- macros %>%  
  mutate(order = case_when(  
    str_detect(family, "Viviparidae") ~ "Architaenioglossa",   
    str_detect(family, "Tricorythidae") ~ "Ephemeroptera",   
    str_detect(family, "Conchostraca") ~ "Crustacea",   
    str_detect(family, "Gordioida") ~ "Gordioida",  
    str_detect(family, "Enchytraeidae") ~ "Haplotaxida",   
    str_detect(family, "Naididae") ~ "Haplotaxida",    
    str_detect(family, "Lymnaeidae") ~ "Hygrophila",   
    str_detect(family, "Physidae") ~ "Hygrophila",   
    str_detect(family, "Planorbidae") ~ "Hygrophila",   
    str_detect(family, "Hydrobiidae") ~ "Littorinimorpha",   
    str_detect(family, "Triopsidae") ~ "Notostraca",  
    str_detect(family, "Glossiphoniidae") ~ "Rhynchobdellida",  
    str_detect(family, "Sphaeriidae") ~ "Sphaeriida",   
    str_detect(family, "Hydracarina") ~ "Trombidiformes",  
    str_detect(family, "Unionidae") ~ "Unionida",  
    str_detect(family, "Corbiculidae") ~ "Venerida",  
    str_detect(order, "Col. Elmidae") ~ "Coleoptera",  
    str_detect(order, "Coleptera") ~ "Coleoptera",   
    str_detect(order, "^Dip.") ~ "Diptera",  
    str_detect(order, "Nematomorpha") ~ "Gordioida",  
    str_detect(order, "^Ann") ~ "Haplotaxida",   
    str_detect(order, "megaloptera") ~ "Megaloptera",       
    str_detect(order, "Platyhelminthes") ~ "Tricladida",  
    str_detect(order, "^Acari") ~ "Trombidiformes",   
    str_detect(order, "Trombidforms") ~ "Trombidiformes",   
    str_detect(order, "Venoroidea") ~ "Venerida",   
    str_detect(order, "Unknown in the data") ~ "NA",  
    TRUE ~ order)) %>%  
  arrange(order) %>%  
    na_if("NA")   

```

```{r fix_taxa_names-class}

# used internet to look up class from order below  

macros <- macros %>%  
    mutate(class = case_when(  
    str_detect(order, "Trombidiformes") ~ "Arachnida",  
    str_detect(order, "Sphaeriida") ~ "Bivalvia",  
    str_detect(order, "Unionida") ~ "Bivalvia",  
    str_detect(order, "Venerida") ~ "Bivalvia",  
    str_detect(order, "Notostraca") ~ "Branchiopoda",  
    str_detect(order, "Haplotaxida") ~ "Clitellata",  
    str_detect(order, "Rhynchobdellida") ~ "Clitellata",  
    str_detect(order, "Crustacea") ~ "Crustacea",  
    str_detect(order, "Decapoda") ~ "Crustacea",  
    str_detect(order, "Collembola") ~ "Entognatha",  
    str_detect(order, "Architaenioglossa") ~ "Gastropoda",  
    str_detect(order, "Anthomedusae") ~ "Hydrozoa",  
    str_detect(order, "Coleoptera") ~ "Insecta",  
    str_detect(order, "Diptera") ~ "Insecta",  
    str_detect(order, "Ephemeroptera") ~ "Insecta",  
    str_detect(order, "Hemiptera") ~ "Insecta",  
    str_detect(order, "Hymenoptera") ~ "Insecta",  
    str_detect(order, "Lepidoptera") ~ "Insecta",  
    str_detect(order, "Megaloptera") ~ "Insecta",  
    str_detect(order, "Odonata") ~ "Insecta",  
    str_detect(order, "Plecoptera") ~ "Insecta",  
    str_detect(order, "Trichoptera") ~ "Insecta",  
    str_detect(order, "Gastropoda") ~ "Gastropoda",  
    str_detect(order, "Hygrophila") ~ "Gastropoda",  
    str_detect(order, "Littorinimorpha") ~ "Gastropoda",  
    str_detect(order, "Amphipoda") ~ "Malacostraca",  
    str_detect(order, "Gordioida") ~ "Nematomorpha",  
    str_detect(order, "Nematoda") ~ "Nematoda",  
    str_detect(order, "Nematodes") ~ "Nematoda",  
    str_detect(order, "Tricladida") ~ "Rhabditophora")) %>%  
  select(class, everything()) %>%  
  arrange(class, order, family, genus) %>%  
    na_if("NA")  %>%    
  filter(!is.na(class))  

```

```{r fix_missed_taxa_names}

# make last taxon fix====   
macros <- macros %>%  
  mutate(genus = case_when(  
    str_detect(family, "Polymitarcyidae") ~ "Ephoron sp.",  
    TRUE ~ genus)) %>%  
  # rename misnamed samples   
  rename(bea2b6 = bcr2b6) %>%  
  rename(bea2d7 = bcr2d7) %>%  
  rename(wok4a6 = wdk4a6) %>%  
  rename(wok4b5 = wdk4b5) %>%  
  rename(wok4d7 = wdk4d7) %>%  
  rename(whi5t6 = whr5t6) %>%  
  rename(whi5u6 = whr5u6) %>%  
  rename(whi3p6 = wtr3p6) %>%  
  rename(whi4a8 = wtr4a8)   

```

```{r data_check-manual}

# 1. get sample names====  
samples <- macros %>%  
  pivot_longer(-c(class, order, family, genus),  
               names_to = "samples",   
               values_to = "count") %>%   
  select(samples) %>%  
  distinct()  %>%  
  arrange(samples)  

# 2. create macros_check====  
# note this is a manual approach to checking data  
macro_ck <- macros %>%  
  select(class:genus, starts_with("wol")) %>%  
  distinct() %>%  
   mutate(total = select(., wol1a6:wol1s6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0)  

count_ck <- macros_ck %>%  
  select(-total) %>%  
  summarise_if(is.numeric, sum, na.rm = TRUE) %>%  
  mutate(scratch = "scratch") %>%  
  pivot_longer(-scratch, names_to = "station", values_to = "count") %>%  
  select(-scratch) %>%  
  arrange(station)  

# manual check of data vs spreadsheets used to produce the data====  
# sample  data/validated count  
# amh1a7  122    
# amh1b6   97     
# amh1d7   98      
# amh1p6   58     
# amh1v6  107     
# bea1a6  120     
# bea1b6  108     
# bea1d7  100     
# bea1t6  372    
# bea1u6  871     
# bea2b6  105    
# bea2d7  100     
# bea2t6  137     
# bea2u6   58      
# bea3a6   77     
# bea3d8  100    
# bea3t6  132    
# bea3u6   97     
# bel1a6	120  
# bel1b6	 90  
# bel1d8	100  
# bel1t6	156  
# bel1u6	 87  
# bel2b6	 92  
# bel2d8	 97  
# bel2t6	141  
# bel2u6	 85  
# blp1a7	149  
# blp1b7	102  
#	blp1d8	100  
#	blp1r6	113  
#	blp1t	  159  
#	blp1u6	103  
# buz1a7	168  
#	buz1d8	100  
#	buz1r6	144  
#	buz1u6	 98  
# chr1b7	 99  
#	chr1d8	 93  
#	chr1s6	104  
#	chr2s6	104  
# cor1b7	 93  
#	cor1d7	 93  
#	cor1u6	 92  
# cra1a6	148  error n=160  
#	cra1b6	 96  
#	cra1d8	 95  
#	cra1t6	177  
#	cra1u6	127  
# ean1b7	112  
#	ean1d8	104  
#	ean1t6	270 error n=265  
#	ean1u6	137 error n=121  
#	ean2d7	 98  
# ean2u6	 95  
# ldc1a6	111 check historical  
#	ldc1d7	 92 check historical  
# lon1b7	110  
#	lon1u6	207 error n=213  
# lwr1a6	206  
#	lwr1b5	 95   
#	lwr1d8	101  
#	lwr1r6	167  
#	lwr1s7	100  
#	lwr1s7_dup   find this one
#	lwr1t6	117  
#	lwr1v6	 85  
#	lwr2a6	 65  
#	lwr2d7	110  
#	lwr2r6	 97  error missing!  
#	lwr2s7	181  
#	lwr2t6	128  
#	lwr2t6_dup	125  
#	lwr2v6	 94  
#	lwr3a6	168  
#	lwr3d7	103  
#	lwr3r6	113  
#	lwr3r6_dup	106  
#	lwr3s8	121  
#	lwr3t	   91  
#	lwr3v6	113  
#	lwr4a6	 48  
#	lwr4d7	100  
#	lwr4s8	165  
#	lwr4t6	220  

# mer1a7	189  
#	mer1b6	 95  
#	mer1d8	 71 error n=102  
#	mer1p6	134  
#	mer1t8	397  
#	mer1v6	124  
#	mer3a7	 83  
#	mer3d7	 76  
#	mer3p6	 83  
#	mer3t8	 92  
#	mer3u6	134  
#	mer3v6	207  
#	mer4p6	 76  
#	mer4t8	182  
#	mer4u6	129  
#	mer4v6	177  
# nfl1a7	152  
#	nfl1b6	 98  
#	nfl1b7	 84  
#	nfl1d8	 78  
#	nfl1p6	139  
#	nfl1v6	204  
# pas1a7	132  
#	pas1d8	100  
#	pas1r6	118  
#	pas1t6	154  
#	pas1u6	196  
#	pas2a6	138  
#	pas2b7	117  
#	pas2d8	 99  
#	pas2r6	115 # error n=116  
#	pas2t6	183  
#	pas2u6	114  
#	pas3a8	158  
#	pas3b7	107  
# pas3d8	103  
#	pas3r6	 73   
#	pas3t6	107  
#	pas3u6	 98  
# por1a6	110  
#	por1b7	61  error n=67  
#	por1c8	54  
#	por1e7	107  
#	por1r6	87  error n=90  
#	por1s6	111  
#	por1t6	96  error n=104  
#	por2a6	70  
#	por2b6	92  
#	por2d7	100  
#	por2d7_dup	99  
#	por2r6	107  
#	por2s6	124  
#	por2t6	101  
#	por2u6	302  
#	por2v6	116  
#	por3a7	127  
#	por3b5	110  
#	por3r6	115  
#	por3s6	104  
#	por3s6_dup	98  
#	por3t6	146  
#	por3u6	184  
#	por3v6	129  
# pot1a7	102 error n=103   
#	pot1b6	 98  
#	pot1d7	 97  
#	pot1u6	159  
# red1a7	223  
#	red1b8	 46  
#	red1d7	100  
#	red1p6	107  
#	red1v6	109  
#	wcc1a67	89  
#	wcc1d7	91  
#	wcc1s6	80  
#	wcc1t6	92  
#	wcc2a6_7	19  
#	wcc2b6	91  
#	wcc2d7	90  
#	wcc2s6	85  
#	wcc2t6	451  
#	wcc3d7	32  
#	wcc3s6	94  
#	wcc3t6	99  
# whi1a7	109 # error n=146  
#	whi1b6	118  
#	whi1d7	100  
#	whi1s6	122  
#	whi2a7	74  
#	whi2b5	108  
#	whi2s6	145  
#	whi3p6	96  
#	whi4a8	35 check historical  
#	whi5t6	91  
#	whi5u6	105  
# wok1a6	139  
#	wok1b5	115  
#	wok1r6	319  
#	wok1s6	113  
#	wok1t6	102  
#	wok2a7	121  
#	wok2b6	 96  
#	wok2r6	114  
#	wok2s6	154  
#	wok2s6_2_separate_count_keep	95  
#	wok2t6	173  
#	wok2u6	645  
#	wok2v6	178  
#	wok3a6	 31  
#	wok3b7	 94  
#	wok3r7	 95  
#	wok3s6	166  
#	wok3t6	136  
#	wok4a6	 92  
#	wok4b5	 23  
#	wok4d7	 99  
#	wok4r6_7	102  
#	wok4s6	 77  
#	wok4t6	132  
#	wok4u6	 94  
#	wok4v6	 90  
# wol1a6	147
#	wol1b5	92
#	wol1d7	95
#	wol1s6	198

```

```{r split_by_stream}

# need to get the right count -- split by stream   

# 1. american_horse split====  
amh <- macros %>%  
  select(class:genus, starts_with("amh")) %>%  
   mutate(total = select(., amh1a7:amh1v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 2. bear creek split====  
bea <- macros %>%  
  select(class:genus, starts_with("bea")) %>%  
   mutate(total = select(., bea1a6:bea3u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 3. bear in the lodge split====  
bel <- macros %>%  
  select(class:genus, starts_with("bel")) %>%  
   mutate(total = select(., bel1a6:bel2u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 4. black pipe split====  
blp <- macros %>%  
  select(class:genus, starts_with("blp")) %>%  
   mutate(total = select(., blp1a7:blp1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 5. bear in the lodge split====  
buz <- macros %>%  
  select(class:genus, starts_with("buz")) %>%  
   mutate(total = select(., buz1a7:buz1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 6. cheyenne river split====  
chr <- macros %>%  
  select(class:genus, starts_with("chr")) %>%  
   mutate(total = select(., chr1b7:chr2s6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 7. buzzard creek split====  
buz <- macros %>%  
  select(class:genus, starts_with("buz")) %>%  
   mutate(total = select(., buz1a7:buz1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 8. cheyenne river split====  
chr <- macros %>%  
  select(class:genus, starts_with("chr")) %>%  
   mutate(total = select(., chr1b7:chr2s6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 9. corn creek split====  
cor <- macros %>%  
  select(class:genus, starts_with("cor")) %>%  
   mutate(total = select(., cor1b7:cor1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 10. craven creek split====  
cra <- macros %>%  
  select(class:genus, starts_with("cra")) %>%  
   mutate(total = select(., cra1a6:cra1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 11. eagle nest creek split====  
ean <- macros %>%  
  select(class:genus, starts_with("ean")) %>%  
   mutate(total = select(., ean1b7:ean2u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 12. lost dog creek split====  
ldc <- macros %>%  
  select(class:genus, starts_with("ldc")) %>%  
   mutate(total = select(., ldc1a6:ldc1d7) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 13. long creek split====  
lon <- macros %>%  
  select(class:genus, starts_with("lon")) %>%  
   mutate(total = select(., lon1b7:lon1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 14. little white river split====  
lwr <- macros %>%  
  select(class:genus, starts_with("lwr")) %>%  
   mutate(total = select(., lwr1a6:lwr4t6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 15. medicine root split====  
mer <- macros %>%  
  select(class:genus, starts_with("mer")) %>%  
   mutate(total = select(., mer1a7:mer4v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 16. no flesh split====  
nfl <- macros %>%  
  select(class:genus, starts_with("nfl")) %>%  
   mutate(total = select(., nfl1a7:nfl1v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 17. pass creek split====  
pas <- macros %>%  
  select(class:genus, starts_with("pas")) %>%  
   mutate(total = select(., pas1a7:pas3u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 18. porcupine creek split====  
por <- macros %>%  
  select(class:genus, starts_with("por")) %>%  
   mutate(total = select(., por1a6:por3v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 19. potato creek split====  
pot <- macros %>%  
  select(class:genus, starts_with("pot")) %>%  
   mutate(total = select(., pot1a7:pot1u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 20. redwater split====  
red <- macros %>%  
  select(class:genus, starts_with("red")) %>%  
   mutate(total = select(., red1a7:red1v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 21. white clay creek split====  
wcc <- macros %>%  
  select(class:genus, starts_with("wcc")) %>%  
   mutate(total = select(., wcc1a67:wcc3t6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 22. redwater split====  
whi <- macros %>%  
  select(class:genus, starts_with("whi")) %>%  
   mutate(total = select(., whi1a7:whi5u6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 23. wounded knee creek split====  
wok <- macros %>%  
  select(class:genus, starts_with("wok")) %>%  
   mutate(total = select(., wok1a6:wok4v6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

# 24. wolf creek split====  
wol <- macros %>%  
  select(class:genus, starts_with("wol")) %>%  
   mutate(total = select(., wol1a6:wol1s6) %>%  
            rowSums(na.rm = TRUE)) %>%  
  filter(total != 0) %>%  
  select(-total) %>%  
  group_by(class, order, family, genus) %>%  
  summarize_if(is.numeric, mean, na.rm = TRUE) %>%  
  ungroup()  

```

```{r join_splits1}

# need to join splits sequentially -- otherwise duplicates  
join1 <- full_join(amh, bea,  
                  by = c("class", "order", "family", "genus"))  

join2 <- full_join(bel, blp,  
                  by = c("class", "order", "family", "genus"))  

join3 <- full_join(buz, chr,  
                  by = c("class", "order", "family", "genus"))  

join4 <- full_join(cor, cra,  
                  by = c("class", "order", "family", "genus"))  

join5 <- full_join(ean, ldc,  
                  by = c("class", "order", "family", "genus"))  

join6 <- full_join(lon, lwr,  
                  by = c("class", "order", "family", "genus"))  

join7 <- full_join(mer, nfl,  
                  by = c("class", "order", "family", "genus"))  

join8 <- full_join(pas, por,  
                  by = c("class", "order", "family", "genus"))  

join9 <- full_join(pot, red,  
                  by = c("class", "order", "family", "genus"))  

join10 <- full_join(wcc, whi, 
                  by = c("class", "order", "family", "genus"))  

join11 <- full_join(wok, wol,  
                  by = c("class", "order", "family", "genus"))  

# clean up global environment====  
rm(amh,  
   bea,  
   bel,  
   blp,  
   buz,  
   chr,  
   cor,  
   cra,  
   ean,  
   ldc,  
   lon,  
   lwr,  
   mer,  
   nfl,  
   pas,  
   por,  
   pot,  
   red,  
   wcc,  
   whi,  
   wok,  
   wol)  

```

```{r join_splits2}

# contininue to join splits sequentially   
join12 <- full_join(join1, join2,  
                    by = c("class", "order", "family", "genus"))  

join13 <- full_join(join3, join4,  
                    by = c("class", "order", "family", "genus"))   

join14 <- full_join(join5, join6,  
                    by = c("class", "order", "family", "genus"))  

join15 <- full_join(join7, join8,  
                    by = c("class", "order", "family", "genus"))   

join16 <- full_join(join9, join10,  
                    by = c("class", "order", "family", "genus"))  

rm(join1,  
   join2,  
   join3,  
   join4,  
   join5,  
   join6,  
   join7,  
   join8,  
   join9,  
   join10)  

```

```{r join_splits3}

# continue to join splits sequentially  
join17 <- full_join(join11, join12,  
                    by = c("class", "order", "family", "genus"))  

join18 <- full_join(join13, join14,  
                    by = c("class", "order", "family", "genus"))   

join19 <- full_join(join15, join16,  
                    by = c("class", "order", "family", "genus"))  

rm(join11,  
   join12,  
   join13,  
   join14,  
   join15,  
   join16)  

```

```{r join_splits4}

# 1. final sequential joins====  
join20 <- full_join(join17, join18,  
                    by = c("class", "order", "family", "genus"))  

macro_ck <- full_join(join19, join20,  
                    by = c("class", "order", "family", "genus"))  

# 2. check results====  
count_ck <- macro_ck %>%  
  summarise_if(is.numeric, sum, na.rm = TRUE) %>%  
  mutate(scratch = "scratch") %>%  
  pivot_longer(-scratch, names_to = "station", values_to = "count") %>%  
  select(-scratch) %>%  
  arrange(station)  

# results -- looks ok  

macros <- macro_ck  

# clean up results====  
rm(join17,  
   join18,  
   join19,  
   join20)  

```

```{r fix_counts}

# 1. import count data from original Excel spreadsheets====  
macro_ck <- import("data/macro_count.csv") %>%  
  mutate(sample_id = str_remove_all(sample_id, "\\#")) %>%  
  mutate(sample_id = str_trim(sample_id))  

count_ck <- full_join(macro_ck, count_ck,  
                       by = c("sample_id" = "station")) %>%  
  rename(count_orig = count.x) %>%  
  rename(count_cleaned = count.y) %>%  
  mutate(diff = count_cleaned - count_orig)  %>%  
  filter(diff != 0)  

# count_ck results  
# sample_id  count_orig  count_cleaned  diff  checked  
#	 pas2r6	      115	      111.5	        -3.5  
#	 por1a6	      110	      108.5	        -1.5  

# 2. check errors against Excel spreadsheets  
macro_ck <- macros %>%  
  select(class:genus,  
         pas2r6,  
         por1a6) %>%  
  arrange(pas2r6,  
          por1a6)  

# 3. update macros as test data  
macro_ck <- macros %>%  
  # arrange by station ids 
  select(class:genus,  
         amh1a7:lwr4t6,  
         mer1a7, mer1b6,  
         mer1d8,  
         mer1p6: wol1s6) %>%  
  # fix errors in data   
  mutate(pas2r6 = case_when(  
    family == "Baetidae" ~ 7,  
    TRUE ~ pas2r6)) %>%  
  mutate(por1a6 = case_when(  
    family == "Glossiphoniidae" ~ 3,  
    TRUE ~ por1a6)) %>%  
  # remove NaN & decimals  
  mutate_if(is.numeric, as.integer)  

# 4. save final results & clean up  
macros <- macro_ck  

rm(check_vars,  
   count_ck,  
   macro_ck,  
   samples)  

```

```{r data_check-duplicates}

# test for duplicates  
dups_ck <- macros %>%  
  distinct()  

```

```{r clean_year}

# 1. arrange site names, dates, notes====   
# pivot the df longer to fix year variable  
macros_wide <- macros  

macros <- macros_wide %>%  
  pivot_longer(-c(class, order, family, genus),  
               values_to = "count") %>%  
  # make a watershed codes  
  separate(name, c("wtshd","scratch"), 3, remove = FALSE) %>%  
  mutate(wtshd = toupper(wtshd)) %>%  
  # make site codes  
  separate(scratch, c("site_cd", "scratch"), 1) %>%  
  unite("site", wtshd:site_cd, remove = FALSE, sep = "") %>%  
  # make year codes  
  separate(scratch, c("yr_cd", "scratch"), 1) %>%  
  # make month codes  
  separate(scratch, c("month", "notes"), 1) %>%  
  mutate(notes = case_when(  
    notes == "" ~ "NA",  
    TRUE ~ notes)) %>%  
  na_if("NA")  

# 2.0 create year variable====   
# 2.1 make a look-up table for year  
yr_look_up <- macros %>%  
  select(yr_cd) %>%  
  distinct() %>%  
  arrange(yr_cd) %>%  
  mutate(year = case_when(  
    yr_cd == "a" ~ 1993,  
    yr_cd == "b" ~ 1994,  
    yr_cd == "c" ~ 1995,  
    yr_cd == "d" ~ 1996,  
    yr_cd == "e" ~ 1997,  
    yr_cd == "p" ~ 2008,  
    yr_cd == "r" ~ 2010,  
    yr_cd == "s" ~ 2011,  
    yr_cd == "t" ~ 2012,  
    yr_cd == "u" ~ 2013,  
    yr_cd == "v" ~ 2014))  

# 2.2 join look-up table  
macros <- left_join(macros, yr_look_up,  
                     by = "yr_cd") %>%  
  select(class:genus, site, year, month, notes, count, name)  

rm(yr_look_up)  

```

```{r standardize_site_names}

# 1 get list of samples====  
site_list <- macros %>%  
  select(year, site, month, notes, name) %>%  
  distinct() %>%  
  arrange(year, site)  

# 2. change names of sites prior to 2000====  
#  these were often called something else
site_hist <- site_list %>%  
  filter(year < 2000) %>%  
  arrange(name)  %>%  
  # standardize site id    
  separate(name, c("wtshd","scratch"), 3) %>%  
  arrange(wtshd) %>%  
  mutate(wtshd = case_when(  
    wtshd == "amh" ~ "amh",  
    wtshd == "bcr" ~ "bea",  
    wtshd == "blc" ~ "bel",  
    wtshd == "bpc" ~ "blp",  
    wtshd == "bzc" ~ "buz",  
    wtshd == "chr" ~ "che",  
    wtshd == "cnc" ~ "cor",  
    wtshd == "crc" ~ "cra",  
    wtshd == "enc" ~ "ean",  
    wtshd == "ldc" ~ "lod",  
    wtshd == "loc" ~ "lon",  
    wtshd == "lwr" ~ "lwr",  
    wtshd == "mrc" ~ "mer",  
    wtshd == "nfc" ~ "nfl",  
    wtshd == "poc" ~ "pot",  
    wtshd == "por" ~ "por",  
    wtshd == "psc" ~ "pas",  
    wtshd == "rdw" ~ "red",  
    wtshd == "wcc" ~ "wcc",  
    wtshd == "wfc" ~ "wol",  
    wtshd == "wtr" ~ "whi",  
    wtshd == "wdk" ~ "wok",  
    TRUE ~ wtshd)) %>%  
  unite("id", c(wtshd, scratch), sep = "") %>%  
  mutate(id = case_when(  
    id == "ean2d7" ~ "ean2d8",  # update site name with collect date  
    TRUE ~ id))  

```

```{r clean_dates-historical}

# 1. get historical data to get sampling dates====  
sample_id_dates_hist <- import("data/sample_id_dates.csv") %>%  
  # make updated id vars by splitting, updating, and rejoining  
  separate(id, c("wtshd","scratch"), 3) %>%  
  arrange(wtshd) %>%  
  mutate(wtshd = case_when(  
    wtshd == "amh" ~ "amh",  
    wtshd == "bcr" ~ "bea",  
    wtshd == "blc" ~ "bel",  
    wtshd == "bpc" ~ "blp",  
    wtshd == "bzc" ~ "buz",  
    wtshd == "chr" ~ "che",  
    wtshd == "cnc" ~ "cor",  
    wtshd == "crc" ~ "cra",  
    wtshd == "enc" ~ "ean",  
    wtshd == "ldc" ~ "lod",  
    wtshd == "loc" ~ "lon",  
    wtshd == "lwr" ~ "lwr",  
    wtshd == "mrc" ~ "mer",  
    wtshd == "nfc" ~ "nfl",  
    wtshd == "poc" ~ "pot",  
    wtshd == "por" ~ "por",  
    wtshd == "psc" ~ "pas",  
    wtshd == "rdw" ~ "red",  
    wtshd == "wcc" ~ "wcc",  
    wtshd == "wfc" ~ "wol",  
    wtshd == "wtr" ~ "whi",  
    wtshd == "wdk" ~ "wok",  
    TRUE ~ wtshd)) %>%  
  unite("id", c(wtshd, scratch), sep = "") %>%  
  mutate(id = case_when(  
    id == "ean2d7" ~ "ean2d8",  
    TRUE ~ id)) %>%  
  mutate(id = case_when(  
    id == "wcc1a6_7" ~ "wcc1a7",  
    id == "wcc2a6_7" ~ "wcc1a7",  
    TRUE ~ id)) %>%  
  mutate(collect_date = case_when(  
    id == "wcc1a7" ~ "July 11 1993",  
    id == "wcc2a7" ~ "July 11 1993",  
    TRUE ~ collect_date)) %>%  
    mutate(notes = case_when(  
    id == "wcc1a7" ~ "Date recorded as 2 11 1993 -- changed to fit WHI1",  
    id == "wcc2a7" ~ "Date recorded as 2 11 1993 -- changed to fit WHI1",  
    TRUE ~ notes)) %>%  
  separate(collect_date, c("month", "day", "year"), 
           fill = "right",  
           remove = FALSE) %>%  
  mutate(month = case_when(  
    str_detect(month, "^May") ~ "5",   
    str_detect(month, "^Jun") ~ "6",   
    str_detect(month, "^Jul") ~ "7",   
    str_detect(month, "^Aug") ~ "8",   
    TRUE ~ month))  

# 2. join and update sample id dates -- historical====  
site_hist <- full_join(site_hist, sample_id_dates_hist,  
                  by = "id") %>%  
  # rename variables  
  rename(site_dups = notes.x) %>%  
  rename(notes = notes.y) %>%  
  rename(day.y = day) %>%  
  # filter out the post 2000 data -- checked and it is ok  
  filter(!is.na(site)) %>%  
  # check and year data -- looks ok  
  mutate(year_ck = year.x == year.y) %>%  
  select(-c(year.y, year_ck)) %>%  
  # update site names & dups  
  mutate(site = case_when(  
    site == "WDK4" ~ "WOK4",  
    site == "WTR4" ~ "WHI4",  
    site == "BCR2" ~ "BEA2",  
    TRUE ~ site)) %>%  
  mutate(site_dups = case_when(  
    site == "WCC1" ~ "NA",  
    site == "WCC2" ~ "NA",  
    TRUE ~ site_dups)) %>%  
  mutate(site_dups = na_if(site_dups, "NA")) %>%  
  arrange(year.x, site) %>%  
  # update missing collect dates & notes based on nearby sites  
  mutate(id = case_when(  
    id == "wcc1a67" ~ "wcc1a6",  
    id == "wcc2a6_7" ~ "wcc2a6",  
    TRUE ~ id)) %>%  
  mutate(collect_date = case_when(  
    id == "lwr2a6" ~ "June 15 1993",  
    id == "lwr4a6" ~ "June 16 1993",  
    id == "wcc1a6" ~ "July 11 1993",  
    id == "wcc2a6" ~ "July 11 1993",  
    id == "wok1a6" ~ "June 15 1993",  
    id == "wok2a7" ~ "July 11 1993",  
    id == "wok3a6" ~ "June 04 1993",  
    id == "wok4a6" ~ "June 04 1993",  
    id == "lon1b7" ~ "July 5 1994",  
    id == "wok1b5" ~ "May 23 1994",  
    id == "wok2b6" ~ "June 01 1994",  
    id == "wok3b7" ~ "July 26 1994",  
    id == "wok4b5" ~ "May 25 1994",  
    id == "lwr2d7" ~ "July 25 1996",  
    id == "pas2d8" ~ "August 13 1996",  
    id == "por2d7_dup" ~ "July 30 1996",   
    id == "por2d7" ~ "July 16 1996",       
    id == "wok4d7" ~ "July 16 1996",      
    TRUE ~ collect_date)) %>%  
  mutate(notes = case_when(  
    id == "lwr2a6" ~ "collect date from lwr1a6",  
    id == "lwr4a6" ~ "collect date from lwr3a6",  
    id == "wcc1a6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wcc2a6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok1a6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok2a7" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok3a6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok4a6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "lon1b7" ~ "collect date from ean1b7",  
    id == "wok1b5" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok2b6" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok3b7" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "wok4b5" ~ "collect date from Excel - Historical Taxa Metrics",  
    id == "lwr2d7" ~ "collect date from lwr3d7",  
    id == "pas2d8" ~ "collect date from pas1d8",  
    id == "por2d7_dup" ~ "collection dates were flipped",  
    id == "por2d7" ~ "collection dates were flipped",  
    id == "wok4d7" ~ "collect date from Excel - Historical Taxa Metrics",  
    TRUE ~ notes)) %>%  
  separate(collect_date, c("month", "day", "year"),  
           fill = "right",  
           remove = FALSE) %>%  
  mutate(month = case_when(  
    str_detect(month, "^May") ~ "5",   
    str_detect(month, "^Jun") ~ "6",   
    str_detect(month, "^Jul") ~ "7",   
    str_detect(month, "^Aug") ~ "8",   
    TRUE ~ month)) %>%  
  # check date results on table -- looks ok  
  select(year, year.x,  
         month, month.x, month.y,  
         day, day.y,  
         everything()) %>%  
  # make a final date variable and arrange vars  
  unite("date", year, month, day) %>%  
  mutate(date = ymd(date)) %>%  
  select(date,  
         site,  
         id,  
         notes)  

# clean up====  
rm(sample_id_dates_hist)  

```

```{r check_dates-historical}

# 1. clean prior_2000 data====  
#    note -- joined below and cleaned up these data  
site_hist <- site_hist %>%  
  mutate(site = case_when(  
    site == "CHR1"  ~ "CHE1",  
    site == "CHR2"  ~ "CHE2",  
    TRUE ~ site)) %>%  
  mutate(id = case_when(  
    id == "mer1b6" ~ "mer1b7",  
#    id == "nfl1b6" ~ "nfl1b7",  
    TRUE ~ id)) %>%  
  mutate(date = case_when(  
    id == "lwr2a6" ~ as.Date("1993-06-16"),  
    id == "wcc2a6" ~ as.Date("1993-06-20"),  
    id == "wol1a6" ~ as.Date("1993-06-04"),  
    id == "lon1b7" ~ as.Date("1994-07-25"),  
    id == "lwr2d7" ~ as.Date("1996-07-18"),  
    id == "mer1b7" ~ as.Date("1994-07-15"),  
    id == "wcc2d7" ~ as.Date("1996-07-02"),  
    id == "wcc2b6" ~ as.Date("1994-06-14"),  
    id == "wol1b5" ~ as.Date("1994-05-25"),  
    id == "wol1d7" ~ as.Date("1996-07-16"),  
    TRUE ~ date)) %>%  
  mutate(notes = case_when(  
    id == "lwr2a6" ~ "",  
    id == "wcc2a6" ~ "split date between two dates",  
    id == "lon1b7" ~ "",  
    id == "lwr2d7" ~ "",  
    id == "nfl1b7" ~ "two samples takes a few days apart",  
    TRUE ~ notes))   

# 2. prepare list of historical dates & clean data====  
site_dates <- import("data/macro_dates.csv") %>% 
  clean_names() %>%  
  select(station:day) %>%  
  rename(site = station) %>%  
  mutate(site = toupper(site)) %>%  
  mutate(scratch = case_when(  
    year == "1993" ~ "a",  
    year == "1994" ~ "b",  
    year == "1995" ~ "c",  
    year == "1996" ~ "d",  
    year == "1997" ~ "e",  
    year == "2008" ~ "p",  
    year == "2010" ~ "r",  
    year == "2011" ~ "s",  
    year == "2012" ~ "t",  
    year == "2013" ~ "u",  
    year == "2014" ~ "v")) %>%  
  mutate(site = case_when(  
    site == "CHR1"  ~ "CHE1",  
    site == "PASS1" ~ "PAS1",  
    site == "PASS2" ~ "PAS2",  
    site == "PASS3" ~ "PAS3",  
    site == "WHR1" ~ "WHI1",  
    site == "WHR2" ~ "WHI2",  
    TRUE ~ site)) %>%  
  separate(site, c("watsd", "loc"), 3,  
           remove = FALSE) %>%  
  mutate(watsd = tolower(watsd)) %>%  
  unite("scratch2", watsd, loc,  
        sep = "") %>%  
  unite("id", scratch2, scratch, month,   
        remove = FALSE,  
        sep = "") %>%  
  unite("date", year, month, day) %>%  
  mutate(date = ymd(date)) %>%  
  select(date, site, id, ecoregion, watershed) %>%  
  filter(id != "NA") %>%  
  # fix names  
  mutate(id = case_when(  
    date == as.Date("1994-06-27") & id == "nfl1b6" ~ "nfl1b7",  
    id == "wcc2a6 or 7" ~ "wcc2a6",  
    TRUE ~ id)) %>%   
  # fix names  
  mutate(date = case_when(  
    id == "wcc2a6" ~ as.Date("1993-06-20"),  
    id == "buz1d8" ~ as.Date("1996-08-13"),  
    TRUE ~ date))  

# 3. check prior_2000 data====   
site_hist_ck <- site_dates %>% 
  filter(date < as.Date("2000-01-01")) 

site_hist_ck1 <- anti_join(site_hist, site_hist_ck,  
                            by = c("date", "site", "id")) %>%  
  select(site:id) %>%  
  mutate(check = case_when(  
    site =="LDC1" ~ "checked",  
    id == "lwr4a6" ~ "checked",  
    id == "wcc1a6" ~ "orig wcc1a67",  
    id == "whi4a8" ~ "small samp size n = 31",  
    id == "pas2d8" ~ "checked",  
    id == "por2d7_dup" ~ "ok",  
    TRUE ~ ""))  

site_hist_ck2 <- anti_join(site_hist_ck, site_hist,  
                            by = c("date", "site", "id")) %>%  
  select(site:id) %>%  
  mutate(check = case_when(  
    id == "bel2a6" ~ "small samp size n = 10",  
    id == "lwr4b7" ~ "small samp size n = 48",  
    id == "por2d7" ~ "ok - duplicated",  
    TRUE ~ ""))  

# 4. join data and check====  
site_hist_fin <- full_join(site_hist, site_hist_ck, 
                           by = c("date", "site", "id")) %>%  
#  filter(id !=  "whi4a8") %>%  
  filter(id !=  "bel2a6") %>%  
  filter(id !=  "lwr4b7")  

# checked -- looks good  
site_hist <- site_hist_fin  

# 5. clean up====  
rm(site_hist_ck,  
   site_hist_ck1,  
   site_hist_ck2,  
   site_hist_fin)  

```

```{r check_dates-post2000}

# 1. clean post-1999 data====  
site_post <- site_list %>%  
  filter(year >= 2000) %>%  
  rename(id = name) %>%  
  mutate(site = case_when(  
    site =="CHR1" ~ "CHE1",  
    site =="CHR2" ~ "CHE2",  
    site =="WTR3" ~ "WHI3",  
    site =="WHR5" ~ "WHI5",  
    TRUE ~ site)) %>%  
  mutate(id = case_when(  
    id == "chr1s6" ~ "che1s6",  
    id == "chr2s6" ~ "che2s6",  
    id == "lwr3t" ~ "lwr3t6",  
    id == "lwr1v6" ~ "lwr1v8",  
    id == "mer4v6" ~ "mer4v7",  
    id == "wtr3p6" ~ "whi3p6",  
    id == "whr5t6" ~ "whi5t6",  
    id == "whr5u6" ~ "whi5u6",  
    id == "wok3r7" ~ "wok3r6",  
    id == "wok4r6_7" ~ "wok4r6",  
    id == "lwr3r6_dup" ~ "delete",  
    id == "lwr1s7_dup" ~ "delete",  
    id == "lwr2t6_dup" ~ "delete",  
    id == "por3s6_dup" ~ "delete",  
    id == "wok2s6_2_separate_count_keep" ~ "delete",  
    TRUE ~ id)) %>%  
  mutate(notes = case_when(  
    notes == "_2_separate_count_keep" ~ "_dup",  
    TRUE ~ notes)) %>%  
  filter(id != "delete")  

# 2. prepare a check list & clean data====  
site_post_ck <- site_dates %>% 
  filter(date > as.Date("2000-01-01")) %>%   
  mutate(site = case_when(  
    site =="WHIT" ~ "WHI3",  
    site =="CHR2" ~ "CHE2",  
    site =="WHR5" ~ "WHI5",  
    id == "lwr3r6" & date == as.Date("2010-06-23") ~ "LWR2",  
    TRUE ~ site)) %>%  
  mutate(id = case_when(  
    id == "chr2s6" ~ "che2s6",  
    id == "lwr2NA6" ~ "lwr2t6",  
    id == "lwr3r6" & date == as.Date("2010-06-23") ~ "lwr2r6",  
    id == "whiTp6" ~ "whi3p6",  
    id == "whr5t6" ~ "whi5t6",  
    id == "whr5u6" ~ "whi5u6",  
    id == "wok4r6 or 7" ~ "wok4r6",  
    TRUE ~ id)) %>%  
  distinct()  

# 3. add missing dates to data====
site_dates_extra <- read_csv("data/macro_dates_xtra.csv") %>%  
  clean_names() %>%  
  select(date:watershed) %>%  
  drop_na() %>%  
  mutate(date = ymd(date))  

site_post_ck <- bind_rows(site_post_ck, site_dates_extra)

# 3. check data & join====  
site_post_ck1 <- anti_join(site_post, site_post_ck,  
                            by = c("site", "id")) %>%  
  select(site:id)  

site_post_ck2 <- anti_join(site_post_ck, site_post, 
                            by = c("site", "id")) %>%  
  select(site:id)  

site_post_fin <- full_join(site_post, site_post_ck, 
                           by = c("site", "id")) %>%  
  select(date, site, id, notes, ecoregion, watershed)  

# checked -- looks good  -- WHI4 - whi4a8 count - n = 31 
site_post <- site_post_fin  

# 5. clean up====  
rm(site_post_ck,  
   site_post_ck1,  
   site_post_ck2,  
   site_post_fin)  

```

```{r join_dates_validate_names}

# 1. bind partially cleaned data and munge a bit more====  
site_list1 <- bind_rows(site_hist, site_post) %>%   
  mutate(site = case_when(  
    site == "WHR5" ~ "WHI5",  
     TRUE ~ site)) %>%  
  mutate(notes = case_when(  
    notes == "" ~ "NA",  
    notes == "_7" ~ "NA",  
    TRUE ~ notes)) %>%  
  mutate(site = case_when(  
    site == "LDC1" ~ "LOD1",  
     TRUE ~ site)) %>%  
  mutate(id = case_when(  
    id == "blp1t" ~ "blp1t6",  
    id == "ldc1a6" ~ "lod1a6",  
    id == "lwr2t6" & date == as.Date("2012-06-23") ~ "delete",  
    id == "por2d7_dup" ~ "delete",  
    id == "wok2s6" & date == as.Date("2011-06-14") ~ "delete",  
    id == "por2d7" & date == as.Date("1996-07-30") ~ "por2d8",  
     TRUE ~ id)) %>%  
  filter(id != "delete") %>%  
  mutate(watershed = case_when(  
    site == "LWR4" ~ "LWR",  
    site == "LOD1" ~ "MER",  
    site == "PAS2" ~ "PAS",  
    site == "POR2" ~ "WOK",  
    site == "WCC1" ~ "upper WHR",  
    watershed == "WHR/WOK" ~ "WOK",  
     TRUE ~ watershed)) %>%  
  mutate(ecoregion = case_when(  
    site == "LOD1" ~ "Great Plains",  
    site == "PAS2" ~ "Great Plains",  
    site == "POR2" ~ "Great Plains",  
    site == "WCC1" ~ "Great Plains",  
    site == "LWR4" ~ "Sandhills",  
     TRUE ~ ecoregion)) %>%  
  mutate(notes = na_if(notes, "NA"))  

# 2. create a checklist & munge a bit====    
site_list2 <- site_list %>%  
  rename(id = name) %>%  
  mutate(site = case_when(  
    site == "BCR2" ~ "BEA2",  
    site == "CHR1" ~ "CHE1",  
    site == "CHR2" ~ "CHE2",  
    site == "LDC1" ~ "LOD1",  
    site == "WDK4" ~ "WOK4",
    site == "WTR3" ~ "WHI3",  
    site == "WTR4" ~ "WHI4",  
    site == "WHR5" ~ "WHI5",  
    TRUE ~ site)) %>%  
  mutate(id = case_when(  
    id == "bea2d6" ~ "bea2d7",  
    id == "bcr2b6" ~ "bea2b6",  
    id == "bcr2d7" ~ "bea2d7",  
    id == "blp1t"  ~ "blp1t6",  
    id == "chr1b7" ~ "che1b7",  
    id == "chr1d8" ~ "che1d8",  
    id == "chr1s6" ~ "che1s6",  
    id == "chr2s6" ~ "che2s6",  
    id == "ean2d7" ~ "ean2d8",  
    id == "ldc1a6" ~ "lod1a6",  
    id == "ldc1d7" ~ "lod1d7",  
    id == "lwr1v6" ~ "lwr1v8",  
    id == "lwr3t" ~ "lwr3t6",  
    id == "mer1b6" ~ "mer1b7",  
    id == "mer4v6" ~ "mer4v7",  
    id == "por2d7_dup" ~ "por2d8",  
    id == "wcc1a67" ~ "wcc1a6",  
    id == "wcc2a6_7" ~ "wcc2a6",  
    id == "wok3r7" ~ "wok3r6",  
    id == "wdk4a6" ~ "wok4a6",  
    id == "wdk4b5" ~ "wok4b5",  
    id == "wdk4d7" ~ "wok4d7",      
    id == "wtr4a8" ~ "whi4a8",  
    id == "wtr3p6" ~ "whi3p6",  
    id == "wtr3p6" ~ "whi3p6",  
    id == "whr5t6" ~ "whi5t6",  
    id == "whr5u6" ~ "whi5u6",  
    id == "wok4r6_7" ~ "wok4r6",  
    id == "lwr1s7_dup" ~ "delete",  
    id == "lwr2t6_dup" ~ "delete",  
    id == "lwr3r6_dup" ~ "delete",  
    id == "por3s6_dup" ~ "delete",  
    id == "wok2s6_2_separate_count_keep" ~ "delete",  
    TRUE ~ id)) %>%  
  filter(id != "delete")  

# 3. check for differences between datasets--should equal zero====  
site_list_ck1 <- anti_join(site_list1, site_list2, 
                            by = c("site", "id"))  
site_list_ck2 <- anti_join(site_list2, site_list1, 
                           by = c("site", "id"))  

# 4. join the two datasets & check notes -- shouldnt have anything useful====  
site_list_fin <- full_join(site_list1, site_list2, 
                           by = c("site", "id")) %>%  
  select(date, site, id, watershed, ecoregion, notes.x, notes.y)  

# 5. make final list & clean up====  
site_list_fin <- site_list_fin %>%  
  select(date:ecoregion)  

rm(site_dates,  
   site_dates_extra,  
   site_hist,  
   site_list,  
#   site_list_check,  
   site_list_ck1,  
   site_list_ck2,  
   site_list1,  
   site_list2,  
   site_post)  

```

```{r join_dates-macros}

# 1. prepare for join -- create a bridge df====  
site_id <- macros_wide %>%  
  select(-c(class:genus)) %>%  
  names() %>%  
  enframe() %>%  
  select(-name) %>%  
# variable names are to reuse code above  
  rename(id = value) %>%  
  mutate(id_new = case_when(  
    id == "bea2d6" ~ "bea2d7",  
    id == "bcr2b6" ~ "bea2b6",  
    id == "bcr2d7" ~ "bea2d7",  
    id == "blp1t"  ~ "blp1t6",  
    id == "chr1b7" ~ "che1b7",  
    id == "chr1d8" ~ "che1d8",  
    id == "chr1s6" ~ "che1s6",  
    id == "chr2s6" ~ "che2s6",  
    id == "ean2d7" ~ "ean2d8",  
    id == "ldc1a6" ~ "lod1a6",  
    id == "ldc1d7" ~ "lod1d7",  
    id == "lwr1v6" ~ "lwr1v8",  
    id == "lwr3t" ~ "lwr3t6",  
    id == "mer1b6" ~ "mer1b7",  
    id == "mer4v6" ~ "mer4v7",  
    id == "por2d7_dup" ~ "por2d8",  
    id == "wcc1a67" ~ "wcc1a6",  
    id == "wcc2a6_7" ~ "wcc2a6",  
    id == "wok3r7" ~ "wok3r6",  
    id == "wdk4a6" ~ "wok4a6",  
    id == "wdk4b5" ~ "wok4b5",  
    id == "wdk4d7" ~ "wok4d7",      
    id == "wtr4a8" ~ "whi4a8",  
    id == "wtr3p6" ~ "whi3p6",  
    id == "wtr3p6" ~ "whi3p6",  
    id == "whr5t6" ~ "whi5t6",  
    id == "whr5u6" ~ "whi5u6",  
    id == "wok4r6_7" ~ "wok4r6",  
    id == "lwr1s7_dup" ~ "delete",  
    id == "lwr2t6_dup" ~ "delete",  
    id == "lwr3r6_dup" ~ "delete",  
    id == "por3s6_dup" ~ "delete",  
    id == "wok2s6_2_separate_count_keep" ~ "delete",  
    TRUE ~ id)) %>%  
  filter(id_new != "delete") %>%  
  mutate(check = id_new == id) %>%  
  # var names are to join site_list_fin to macros  
  rename(name = id) %>%  
  rename(id = id_new)  

# 2. add bridge to site list====  
site_id <- full_join(site_id, site_list_fin,  
                     by = "id") %>%  
  select(-check)  

# 3. prepare to join date and macros data====  
macros_fin <- macros %>%  
  mutate(site = case_when(  
    site == "BCR2" ~ "BEA2",  
    site == "CHR1" ~ "CHE1",  
    site == "CHR2" ~ "CHE2",  
    site == "LDC1" ~ "LOD1",  
    site == "WDK4" ~ "WOK4",  
    site == "WTR3" ~ "WHI3",  
    site == "WTR4" ~ "WHI4",  
    site == "WHR5" ~ "WHI5",  
    TRUE ~ site))  

# 4. join data and macros data===
macros_fin <- full_join(macros_fin, site_id,  
                        by = c("site", "name")) %>%  
  select(site, id, date, class:genus, count, watershed, ecoregion)  

# looks good: macros N = 32,130 & macros_fin N = 32,130  

# 5. check data -- remove duplicated samples====  
macros_ck <- macros_fin %>%  
  select(site, id) %>%  
  distinct()  

macros_ck <- macros_fin %>%  
  filter(is.na(id)) %>%  
  filter(!is.na(count)) %>%  
  arrange(site) %>%  
  mutate(note = case_when(  
    site == "LWR1" ~ "duplicate sample from 2011-07-01",  
    site == "LWR2" ~ "duplicate sample from 2012-06-18",  
    site == "LWR3" ~ "duplicate sample from 2010-06-24",  
    site == "POR3" ~ "duplicate sample from 2011-06-13",  
    site == "WOK2" ~ "near duplicate sample 2011-06-17"))  

macros_ck2 <- macros_fin %>%  
  filter(is.na(id)) %>%  
  filter(is.na(count)) 
  
macros_fin <- macros_fin %>%  
  filter(!is.na(id))  

# clean up global environment  
rm(dups_ck,  
   macros,  
   macros_ck,  
   macros_ck2,  
   macros_wide,  
   site_id)  

```

```{r export_cleaned_data}
export(site_list_fin, "data/station_id_list.csv")  
export(macros_fin, "data/macros_tidy.csv")  

```



