---
title: "CEE790_Presentation"
author: "Charles Jason Tinant"
date: "10/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--
line 1: ~6 
line 2: 

# Mitakyue Oysen - Everything depends on everything else 
* The river *mni xxx* and its valley *xxx* are a continuum 
* 
--> 

#Wopila to Contributors 
## Oglala Lakota College students
Delaine Peterson 
Aaron Rasor 

## OST Environmental Protection Program staff 
Delinda Simmons 
Al Hancock 

## Lakota Elders 
Bryant High Horse 
Wilmur Mesteth 
Charlie White Buffalo 
Marcel Bull Bear 

## PhD Committee Members 
**Dr. Scott Kenner**  
Dr. Suzette Burckhard (SDSU)  
Dr. Kyle Caudle  
Dr. Peter Nelson 
Dr. Foster Sawyer  

## National Science Foundation 
TCUP Yuowanca - HRD xx
OLC-SDSU-SDSMT PreEngineering Educational Collaborative 
OLC-SDSU-SDSMT PreEngineering Educational Collaborative - Phase II

#Presentation Scope 
I plan to discuss:
* a general approach to quantify ecological drought for semiarid streams  
* Discuss data gaps and how to resolve them
* Present key results to date

This presentation won't provide: 
* Detailed descriptions of setting 
* Ecological theory discussion or statistical method rationale  
* Extrapolation of results 



